### ISSUE TITLE
MRPE and MPJPE

### ISSUE THREAD

**Issue by surelyee** [mks0601/3DMPPE_POSENET_RELEASE#10]
hello~
i run your code PoseNet and RootNet. this is the result of MRPE and MPJPE on h36m dataset.
![image](https://user-images.githubusercontent.com/24806238/63250250-cc9ce880-c29d-11e9-8473-9a3e75e52e11.png)
![image](https://user-images.githubusercontent.com/24806238/63250331-fa822d00-c29d-11e9-8231-164e6b52305c.png)
![image](https://user-images.githubusercontent.com/24806238/63250617-a0ce3280-c29e-11e9-9cc5-67bdd3e72ee6.png)

why the result is lower than your paper?  ...maybe i was wrong in some place?..
thanks.

**Comment by mks0601** [comment]
please check which protocol number do you want and change it in `data/Human36M/Human36M.py`.

**Comment by surelyee** [comment]
@mks0601 ok, thanks a lot. i am very interesting to your works. now i have some quesion about your paper.
The MRPE of RootNet is 120.0mm in h36m dataset. the MPJPE with  groundtruth is 53.3mm and without groundtruth is 54.4mm. so i can't understand the only 1mm improvement with groudtruth. but the error of RootNet is 120mm. MPJPE have some relationship with MRPE?
thanks.

**Comment by mks0601** [comment]
Did you read my paper? I think you'd better read it and check definitions of MRPE and MPJPE.

**Comment by surelyee** [comment]
@mks0601  I did read your paper, and watch the definition of MPJPE another once  after your answer hahahha~
so,  your groundtruth meaning whether using human detection for bbox? in section 8.4...

**Comment by mks0601** [comment]
gt bbox + gt root joint location
It is described in the paper
