### ISSUE TITLE
About R and t in h36m

### ISSUE THREAD

**Issue by pangyyyyy** [mks0601/3DMPPE_POSENET_RELEASE#100]
How did you obtain the camera parameters R, t, f, c in H36M parsed data? I've tried to derive the camera parameters from `metadata.XML` provided in the H36M website but I got a different t from the ones in your annotation file.

P.S. I was referred to here by https://github.com/Jeff-sjtu/HybrIK/issues/46

**Comment by mks0601** [comment]
I think what you got it T, and mine is -np.dot(R.transpose(1,0), T.reshape(3,1)).reshape(3)

**Comment by pangyyyyy** [comment]
I see, thanks for the clarification!
