### ISSUE TITLE
Questions about the evaluation on MuPoTS

### ISSUE THREAD

**Issue by Juzezhang** [mks0601/3DMPPE_POSENET_RELEASE#106]
Hello, thank you for your amazing repo. I noticed that you back-project (x,y) pixel + z milimeter to (x,y,z) milimeter in test stage. In 3DPCKrel evaluation case, I am confused whether you use GT z or rootnet output z in your paper. It will be very useful if you could provide more details. Thank a lot.

**Comment by mks0601** [comment]
Hi, I use RootNet output z.

**Comment by Juzezhang** [comment]
Thanks for reply! But I found that in your release code and pretrained model that 81.8 PCKrel maybe obtain by using the GT z which refer from the following code? 
Line 132 https://github.com/mks0601/3DMPPE_POSENET_RELEASE/blob/master/data/MuPoTS/MuPoTS.py#L132

I don't know whether I understand it incorrectly.

**Comment by mks0601** [comment]
Here, root_cam is from rootnet output: https://github.com/mks0601/3DMPPE_POSENET_RELEASE/blob/3f92ebaef214a0eb1574b7265e836456fbf3508a/data/MuPoTS/MuPoTS.py#L91

**Comment by Juzezhang** [comment]
> Here, root_cam is from rootnet output:
> 
> https://github.com/mks0601/3DMPPE_POSENET_RELEASE/blob/3f92ebaef214a0eb1574b7265e836456fbf3508a/data/MuPoTS/MuPoTS.py#L91



> Here, root_cam is from rootnet output:
> 
> https://github.com/mks0601/3DMPPE_POSENET_RELEASE/blob/3f92ebaef214a0eb1574b7265e836456fbf3508a/data/MuPoTS/MuPoTS.py#L91

I got it, Thanks very much!
