### ISSUE TITLE
root-relative discretized depth 

### ISSUE THREAD

**Issue by sunmengnan** [mks0601/3DMPPE_POSENET_RELEASE#109]
https://github.com/mks0601/3DMPPE_POSENET_RELEASE/blob/3f92ebaef214a0eb1574b7265e836456fbf3508a/demo/demo.py#L105
Hi, is the root-relative discretized depth refterring to each joint relative to the previous joint，or all the joints relative to the pelvis joint?

I found there is no negative value in root-relative depth among all the joints, is there something wrong?

**Comment by mks0601** [comment]
Q. is the root-relative discretized depth refterring to each joint relative to the previous joint，or all the joints relative to the pelvis joint?
A. all the joints relative to the pelvis joint.
they are discretized in heatmap space (0~63)
