### ISSUE TITLE
Visualisation Code in MATLAB

### ISSUE THREAD

**Issue by fraserprice** [mks0601/3DMPPE_POSENET_RELEASE#11]
The visualisation really should not be done with MATLAB. Very strange to have essentially all code in Python except visualisation (which could be done with `matplotlib`); is there a specific reason for this?

I really want to review this code as paper looks really cool, but I don't have access to MATLAB (not free software) so fundamentally can't demo it.

**Comment by mks0601** [comment]
This code is written several years ago for other purpose and I just reused it. This is my code and why it should not be done with MATLAB? You can write `matplotlib` code by yourself if you need that.
