### ISSUE TITLE
Typos in the Derivation of d?

### ISSUE THREAD

**Issue by hellojialee** [mks0601/3DMPPE_POSENET_RELEASE#115]
Should the alpha_x = f / p_x?    (l_x,sensor) / p_x
<img width="384" alt="image" src="https://user-images.githubusercontent.com/21237799/149620669-95abd5e3-be28-4bc9-a0e8-827d373597e0.png">

**Comment by mks0601** [comment]
alpha_x = f * p_x

**Comment by hellojialee** [comment]
Thank you for your replying. But the sentence below Equation (1) in the main text says:

> where αx, αy, Areal, and Aimg are focal lengths divided by the per-pixel distance factors (pixel) of x- and y-axes....

Sorry for my silly question.

**Comment by mks0601** [comment]
p_x is 1/per-pixel distance factor

**Comment by hellojialee** [comment]
OK, many thanks~
