### ISSUE TITLE
Could not download human3.6M images

### ISSUE THREAD

**Issue by willie1997** [mks0601/3DMPPE_POSENET_RELEASE#13]
![image](https://user-images.githubusercontent.com/39046939/65232422-b1730200-db03-11e9-91d5-51c9878a4fed.png)

**Comment by mks0601** [comment]
Hmm.. I can still download it. Have you tried `wget https://cv.snu.ac.kr/dataset/3DMPPE/Human36M/images.zip`?

**Comment by jordanhart** [comment]
Having same problem. Download gave up at around 86gb last night, and can't connect to webpage to redownload.

**Comment by mks0601** [comment]
Sorry there was a sudden blackout at out building. The server will be connected in today.

**Comment by mks0601** [comment]
It works now!

**Comment by jordanhart** [comment]
Thanks!
