### ISSUE TITLE
Question about pretrained model used in demo.

### ISSUE THREAD

**Issue by YeonwooSung** [mks0601/3DMPPE_POSENET_RELEASE#137]
Hi.
First of all, thanks a lot for this awesome work.

For the pretrained model that is provided for the demo, which datasets are used for training?

As far as I understand, you have trained 3D-MPPE posenet with multiple subsets of datasets; some are trained on Human3.6 with protocol 1, some are trained on Human3.6 with protocol 2, and some are trained on MPII and MSCOCO.

I was wondering which datasets are used for training this pretrained model.

Thanks.

**Comment by mks0601** [comment]
I think it's trained on MuCo-3DHP+MSCOCO

**Comment by YeonwooSung** [comment]
Thanks!
