### ISSUE TITLE
Demo code for posenet

### ISSUE THREAD

**Issue by wuneng** [mks0601/3DMPPE_POSENET_RELEASE#14]
Hi,
   Thanks for your amazing work.
   I want to test posenet on a single image(already cropped by Detectron).Could you please share a demo script to visualization?

**Comment by bml1g12** [comment]
If it helps, I adapted this little hacked together script. Not elegant like the original code but its functional for a quick test on a single image. The `bbox` is hard coded (its likely best to have it as a square one centered on the human, as that is similar to the training process I believe).  The `skeleton` and `joint_num` is hard coded here for the Human3D+MPII pretrained model.

```
import argparse
from tqdm import tqdm
import numpy as np
import cv2
from config import cfg
import torch
from base import Tester
from utils.vis import vis_keypoints
from utils.pose_utils import flip
import torch.backends.cudnn as cudnn

from dataset import generate_patch_image #BML Added
import torchvision.transforms as transforms

def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument('--gpu', type=str, dest='gpu_ids')
    parser.add_argument('--test_epoch', type=str, dest='test_epoch')
    args = parser.parse_args()

    # test gpus
    if not args.gpu_ids:
        args.gpu_ids = str(np.argmin(mem_info()))

    if '-' in args.gpu_ids:
        gpus = args.gpu_ids.split('-')
        gpus[0] = 0 if not gpus[0].isdigit() else int(gpus[0])
        gpus[1] = len(mem_info()) if not gpus[1].isdigit() else int(gpus[1]) + 1
        args.gpu_ids = ','.join(map(lambda x: str(x), list(range(*gpus))))
    
    assert args.test_epoch, 'Test epoch is required.'
    return args

def prepare_input(imgpath, bbox):
    cvimg = cv2.imread(imgpath, cv2.IMREAD_COLOR | cv2.IMREAD_IGNORE_ORIENTATION)
    if not isinstance(cvimg, np.ndarray):
        raise IOError("Fail to read %s" % imgpath)
    img_height, img_width, img_channels = cvimg.shape

    scale, rot, do_flip, color_scale, do_occlusion = 1.0, 0.0, False, [1.0, 1.0, 1.0], False

    # 3. crop patch from img and perform data augmentation (flip, rot, color scale, synthetic occlusion)
    # Adds black padding and ensured 255x255 dimensions for input even by introducing stretching.
    img_patch, trans = generate_patch_image(cvimg, bbox, do_flip, scale, rot, do_occlusion)

    for i in range(img_channels):
        img_patch[:, :, i] = np.clip(img_patch[:, :, i] * color_scale[i], 0, 255)

    transform = transforms.Compose([ \
        transforms.ToTensor(),
        transforms.Normalize(mean=cfg.pixel_mean, std=cfg.pixel_std)] \
        )

    img_patch = transform(img_patch)

    input_img = img_patch.unsqueeze(0)

    return input_img

def plot_3dkeypoints(pred, skeleton):
    from mpl_toolkits.mplot3d import Axes3D
    import matplotlib.pyplot as plt
    import matplotlib as mpl
    from matplotlib.axes._axes import _log as matplotlib_axes_logger
    mpl.use("TKAgg", warn=False, force=True)
    matplotlib_axes_logger.setLevel('ERROR')

    def set_axes_radius(ax, origin, radius):
        ax.set_xlim3d([origin[0] - radius, origin[0] + radius])
        ax.set_ylim3d([origin[1] - radius, origin[1] + radius])
        ax.set_zlim3d([origin[2] - radius, origin[2] + radius])

    def set_axes_equal(ax):
        '''Make axes of 3D plot have equal scale so that spheres appear as spheres,
        cubes as cubes, etc..  This is one possible solution to Matplotlib's
        ax.set_aspect('equal') and ax.axis('equal') not working for 3D.

        Call this function before plt.show()

        Input
          ax: a matplotlib axis, e.g., as output from plt.gca().
        '''

        limits = np.array([
            ax.get_xlim3d(),
            ax.get_ylim3d(),
            ax.get_zlim3d(),
        ])

        origin = np.mean(limits, axis=1)
        radius = 0.5 * np.max(np.abs(limits[:, 1] - limits[:, 0]))
        set_axes_radius(ax, origin, radius)

    fig = plt.figure()
    ax = fig.add_subplot(111, projection='3d')

    # Convert from plt 0-1 RGBA colors to 0-255 BGR colors for opencv.
    cmap = plt.get_cmap('rainbow')
    colors = [cmap(i) for i in np.linspace(0, 1, len(pred) + 2)]
    colors = [np.array((c[2], c[1], c[0])) for c in colors]

    for i, (x, y, z) in enumerate(pred):
        ax.scatter(x, y, z, c=np.array(colors[i]), marker='o')

    for (joint_a, joint_b) in skeleton:
        ax.plot([pred[joint_a][0], pred[joint_b][0]],
                [pred[joint_a][1], pred[joint_b][1]],
                [pred[joint_a][2], pred[joint_b][2]])

    ax.set_xlabel('X Label')
    ax.set_ylabel('Z Label')
    ax.set_zlabel('Y Label')
    # The model by default predicts x and z to be the the width-wise and length-wise directions of the original image
    # With depth added into the y axis. So this rotation shows the original 2D perspective (i.e. the 2D keypoints)
    ax.view_init(azim=-90, elev=-90)
    ax.legend()
    set_axes_equal(ax)
    plt.show()



def main():

    args = parse_args()
    cfg.set_args(args.gpu_ids)
    cudnn.fastest = True
    cudnn.benchmark = True
    cudnn.deterministic = False
    cudnn.enabled = True

    tester = Tester(args.test_epoch)

    # The pretrained model used is assumed to be  Human36M keypoints and skeleton. Change if a different model is used.
    tester.joint_num = 18
    tester.skeleton = (
        (0, 7), (7, 8), (8, 9), (9, 10), (8, 11), (11, 12), (12, 13), (8, 14), (14, 15), (15, 16), (0, 1), (1, 2), (2, 3),
        (0, 4), (4, 5), (5, 6))
    #tester._make_batch_generator()
    tester._make_model()

    preds = []
    with torch.no_grad():
        itr = 0 # iteration
        imgpath = "./example_images/2019-06-14_22-19-44_1438_5.png"
        bbox = (80, 80, 150, 150)
        input_img = prepare_input(imgpath, bbox)
        # forward
        coord_out = tester.model(input_img)
        print('coord out shape:', coord_out.shape)

        vis = True
        if vis:
            filename = str(itr)
            tmpimg = input_img[0].cpu().numpy()
            tmpimg = tmpimg * np.array(cfg.pixel_std).reshape(3,1,1) + np.array(cfg.pixel_mean).reshape(3,1,1)
            tmpimg = tmpimg.astype(np.uint8)
            tmpimg = tmpimg[::-1, :, :]
            tmpimg = np.transpose(tmpimg,(1,2,0)).copy()
            tmpkps = np.zeros((3,tester.joint_num))
            tmpkps[:2,:] = coord_out[0,:,:2].cpu().numpy().transpose(1,0) / cfg.output_shape[0] * cfg.input_shape[0]
            tmpkps[2,:] = 1
            tmpimg = vis_keypoints(tmpimg, tmpkps, tester.skeleton)
            cv2.imwrite(filename + '_output.jpg', tmpimg)
            cv2.imshow('img', tmpimg)
            cv2.waitKey(0)
            cv2.destroyAllWindows()

        coord_out = coord_out.cpu().numpy()

        vis_3d=True
        if vis_3d:
            pred=coord_out.squeeze() #remove first batch dimension
            plot_3dkeypoints(pred, tester.skeleton)
        preds.append(coord_out)
            
    # evaluate
    preds = np.concatenate(preds, axis=0)


if __name__ == "__main__":
    main()
```

**Comment by wuneng** [comment]
@bml1g12 Thanks for your kind help. I have test your script and the result is unsatisfactory. 
@mks0601  By the way,  i also have implemented a demo. The result is also terrible. I have uploaded both the input images and outputs of the posenet.  
![input_img1](https://user-images.githubusercontent.com/16924094/65411764-46397080-de20-11e9-9d0f-4b345dea7016.jpg)
![input_img2](https://user-images.githubusercontent.com/16924094/65411769-4a658e00-de20-11e9-9313-6c7350bdcaef.jpg)
![output_1](https://user-images.githubusercontent.com/16924094/65411771-4cc7e800-de20-11e9-9ccf-7e73ce9a971b.jpg)

![output_2](https://user-images.githubusercontent.com/16924094/65411774-4e91ab80-de20-11e9-8236-43d5e5eb3ae5.jpg)

**Comment by mks0601** [comment]
I don't think you implemented demo code properly. You'd better check your code with Human3.6M image. After check there is no bug, you can use other images.

**Comment by bml1g12** [comment]
@wuneng I took the image you posted, and ran it through the script I posted:
```
        imgpath = "./example_images/man.jpg"
        bbox = (0,0, 256,256)
```
![image](https://user-images.githubusercontent.com/2605767/65417592-57d94300-de35-11e9-89d4-5683c32ba608.png)

**Comment by wuneng** [comment]
@bml1g12  It's weird.  I will check the code. Thanks for your help.

**Comment by wuneng** [comment]
@bml1g12  I ran the demo you posted many times, still can not get promising result.  My demo and images are uploaded,  i wonder if you can get correct keypoints.  By the way, which pre-trained model do you use?
```
import argparse
from tqdm import tqdm
import numpy as np
import cv2
from config import cfg
import torch
from base import Tester
from utils.vis import vis_keypoints
from utils.pose_utils import flip
import torch.backends.cudnn as cudnn

from dataset import generate_patch_image  # BML Added
import torchvision.transforms as transforms


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument('--gpu', type=str, dest='gpu_ids')
    parser.add_argument('--test_epoch', type=str, dest='test_epoch')
    args = parser.parse_args()

    # test gpus
    if not args.gpu_ids:
        args.gpu_ids = str(np.argmin(mem_info()))

    if '-' in args.gpu_ids:
        gpus = args.gpu_ids.split('-')
        gpus[0] = 0 if not gpus[0].isdigit() else int(gpus[0])
        gpus[1] = len(mem_info()) if not gpus[1].isdigit() else int(gpus[1]) + 1
        args.gpu_ids = ','.join(map(lambda x: str(x), list(range(*gpus))))

    assert args.test_epoch, 'Test epoch is required.'
    return args


def prepare_input(imgpath, bbox):
    cvimg = cv2.imread(imgpath, cv2.IMREAD_COLOR | cv2.IMREAD_IGNORE_ORIENTATION)
    if not isinstance(cvimg, np.ndarray):
        raise IOError("Fail to read %s" % imgpath)
    img_height, img_width, img_channels = cvimg.shape

    scale, rot, do_flip, color_scale, do_occlusion = 1.0, 0.0, False, [1.0, 1.0, 1.0], False

    # 3. crop patch from img and perform data augmentation (flip, rot, color scale, synthetic occlusion)
    # Adds black padding and ensured 255x255 dimensions for input even by introducing stretching.
    img_patch, trans = generate_patch_image(cvimg, bbox, do_flip, scale, rot, do_occlusion)

    for i in range(img_channels):
        img_patch[:, :, i] = np.clip(img_patch[:, :, i] * color_scale[i], 0, 255)

    transform = transforms.Compose([ \
        transforms.ToTensor(),
        transforms.Normalize(mean=cfg.pixel_mean, std=cfg.pixel_std)] \
        )

    img_patch = transform(img_patch)

    input_img = img_patch.unsqueeze(0)

    return input_img


def plot_3dkeypoints(pred, skeleton):
    from mpl_toolkits.mplot3d import Axes3D
    import matplotlib.pyplot as plt
    import matplotlib as mpl
    from matplotlib.axes._axes import _log as matplotlib_axes_logger
    mpl.use("TKAgg", warn=False, force=True)
    matplotlib_axes_logger.setLevel('ERROR')

    def set_axes_radius(ax, origin, radius):
        ax.set_xlim3d([origin[0] - radius, origin[0] + radius])
        ax.set_ylim3d([origin[1] - radius, origin[1] + radius])
        ax.set_zlim3d([origin[2] - radius, origin[2] + radius])

    def set_axes_equal(ax):
        '''Make axes of 3D plot have equal scale so that spheres appear as spheres,
        cubes as cubes, etc..  This is one possible solution to Matplotlib's
        ax.set_aspect('equal') and ax.axis('equal') not working for 3D.

        Call this function before plt.show()

        Input
          ax: a matplotlib axis, e.g., as output from plt.gca().
        '''

        limits = np.array([
            ax.get_xlim3d(),
            ax.get_ylim3d(),
            ax.get_zlim3d(),
        ])

        origin = np.mean(limits, axis=1)
        radius = 0.5 * np.max(np.abs(limits[:, 1] - limits[:, 0]))
        set_axes_radius(ax, origin, radius)

    fig = plt.figure()
    ax = fig.add_subplot(111, projection='3d')

    # Convert from plt 0-1 RGBA colors to 0-255 BGR colors for opencv.
    cmap = plt.get_cmap('rainbow')
    colors = [cmap(i) for i in np.linspace(0, 1, len(pred) + 2)]
    colors = [np.array((c[2], c[1], c[0])) for c in colors]

    for i, (x, y, z) in enumerate(pred):
        ax.scatter(x, y, z, c=np.array(colors[i]), marker='o')

    for (joint_a, joint_b) in skeleton:
        ax.plot([pred[joint_a][0], pred[joint_b][0]],
                [pred[joint_a][1], pred[joint_b][1]],
                [pred[joint_a][2], pred[joint_b][2]])

    ax.set_xlabel('X Label')
    ax.set_ylabel('Z Label')
    ax.set_zlabel('Y Label')
    # The model by default predicts x and z to be the the width-wise and length-wise directions of the original image
    # With depth added into the y axis. So this rotation shows the original 2D perspective (i.e. the 2D keypoints)
    ax.view_init(azim=-90, elev=-90)
    ax.legend()
    set_axes_equal(ax)
    plt.show()


def main():
    args = parse_args()
    cfg.set_args(args.gpu_ids)
    cudnn.fastest = True
    cudnn.benchmark = True
    cudnn.deterministic = False
    cudnn.enabled = True

    tester = Tester(args.test_epoch)

    # The pretrained model used is assumed to be  Human36M keypoints and skeleton. Change if a different model is used.
    tester.joint_num = 18
    tester.skeleton = (
        (0, 7), (7, 8), (8, 9), (9, 10), (8, 11), (11, 12), (12, 13), (8, 14), (14, 15), (15, 16), (0, 1), (1, 2),
        (2, 3),
        (0, 4), (4, 5), (5, 6))
    # tester._make_batch_generator()
    tester._make_model()

    preds = []
    with torch.no_grad():
        itr = 0  # iteration
        imgpath = "in.png"
        bbox = (0, 0, 256, 256)
        input_img = prepare_input(imgpath, bbox)
        # forward
        coord_out = tester.model(input_img)
        print('coord out shape:', coord_out.shape)

        vis = True
        if vis:
            filename = str(itr)
            tmpimg = input_img[0].cpu().numpy()
            tmpimg = tmpimg * np.array(cfg.pixel_std).reshape(3, 1, 1) + np.array(cfg.pixel_mean).reshape(3, 1, 1)
            tmpimg *= 255
            tmpimg = tmpimg.astype(np.uint8)
            tmpimg = tmpimg[::-1, :, :]
            tmpimg = np.transpose(tmpimg, (1, 2, 0)).copy()
            tmpkps = np.zeros((3, tester.joint_num))
            tmpkps[:2, :] = coord_out[0, :, :2].cpu().numpy().transpose(1, 0) / cfg.output_shape[0] * cfg.input_shape[0]
            tmpkps[2, :] = 1
            tmpimg = vis_keypoints(tmpimg, tmpkps, tester.skeleton)
            cv2.imwrite(filename + '_output.jpg', tmpimg)
            # cv2.imshow('img', tmpimg)
            # cv2.waitKey(0)
            # cv2.destroyAllWindows()

        coord_out = coord_out.cpu().numpy()

        vis_3d = False
        if vis_3d:
            pred = coord_out.squeeze()  # remove first batch dimension
            plot_3dkeypoints(pred, tester.skeleton)
        preds.append(coord_out)

    # evaluate
    preds = np.concatenate(preds, axis=0)


if __name__ == "__main__":
    main()
```
![in](https://user-images.githubusercontent.com/16924094/65490153-36349600-dedf-11e9-8426-db75ba9afdc7.png)
![0_output](https://user-images.githubusercontent.com/16924094/65490159-37fe5980-dedf-11e9-9284-8b886c677986.jpg)

**Comment by bml1g12** [comment]
https://cv.snu.ac.kr/research/3DMPPE/model/PoseNet/human3.6m/p2/snapshot_24.pth.tar

**Comment by bml1g12** [comment]
Is in.png 256x256 pixels?

**Comment by mks0601** [comment]
I strongly recommend using Human3.6M image for debugging.

**Comment by wuneng** [comment]
yes, tensor shape is 1 * 3 * 256 * 256. Human3.6M is too large to download. It takes hundreds of hours to download. Thanks for your suggestion.@mks0601

**Comment by bml1g12** [comment]
I mean the input image should be that dimension; my guess is the input
image you are feeding doesn't match the bounding box. If the bounding box
is defined x, y, w, h = (0, 0, 256, 256). You want to ensure this box is
the same length scale as the image itself. E.g. if the raw image was
300x200 you'd need to change the bounding box to ensure the (x,y,w,h)
results in at square box around the subject (maybe 0, 0, 300, 300).

**Comment by wuneng** [comment]
Input image is already cropped and resized to 256 * 256. No pre-processing is needed any more.

**Comment by bml1g12** [comment]
Hmm sorry I'm unsure of the cause of the issue then

**Comment by wuneng** [comment]
It doesn't matter. Thanks any way.

**Comment by SkyJoyTianle** [comment]
> If it helps, I adapted this little hacked together script. Not elegant like the original code but its functional for a quick test on a single image. The `bbox` is hard coded (its likely best to have it as a square one centered on the human, as that is similar to the training process I believe). The `skeleton` and `joint_num` is hard coded here for the Human3D+MPII pretrained model.
> 
> ```
> import argparse
> from tqdm import tqdm
> import numpy as np
> import cv2
> from config import cfg
> import torch
> from base import Tester
> from utils.vis import vis_keypoints
> from utils.pose_utils import flip
> import torch.backends.cudnn as cudnn
> 
> from dataset import generate_patch_image #BML Added
> import torchvision.transforms as transforms
> 
> def parse_args():
>     parser = argparse.ArgumentParser()
>     parser.add_argument('--gpu', type=str, dest='gpu_ids')
>     parser.add_argument('--test_epoch', type=str, dest='test_epoch')
>     args = parser.parse_args()
> 
>     # test gpus
>     if not args.gpu_ids:
>         args.gpu_ids = str(np.argmin(mem_info()))
> 
>     if '-' in args.gpu_ids:
>         gpus = args.gpu_ids.split('-')
>         gpus[0] = 0 if not gpus[0].isdigit() else int(gpus[0])
>         gpus[1] = len(mem_info()) if not gpus[1].isdigit() else int(gpus[1]) + 1
>         args.gpu_ids = ','.join(map(lambda x: str(x), list(range(*gpus))))
>     
>     assert args.test_epoch, 'Test epoch is required.'
>     return args
> 
> def prepare_input(imgpath, bbox):
>     cvimg = cv2.imread(imgpath, cv2.IMREAD_COLOR | cv2.IMREAD_IGNORE_ORIENTATION)
>     if not isinstance(cvimg, np.ndarray):
>         raise IOError("Fail to read %s" % imgpath)
>     img_height, img_width, img_channels = cvimg.shape
> 
>     scale, rot, do_flip, color_scale, do_occlusion = 1.0, 0.0, False, [1.0, 1.0, 1.0], False
> 
>     # 3. crop patch from img and perform data augmentation (flip, rot, color scale, synthetic occlusion)
>     # Adds black padding and ensured 255x255 dimensions for input even by introducing stretching.
>     img_patch, trans = generate_patch_image(cvimg, bbox, do_flip, scale, rot, do_occlusion)
> 
>     for i in range(img_channels):
>         img_patch[:, :, i] = np.clip(img_patch[:, :, i] * color_scale[i], 0, 255)
> 
>     transform = transforms.Compose([ \
>         transforms.ToTensor(),
>         transforms.Normalize(mean=cfg.pixel_mean, std=cfg.pixel_std)] \
>         )
> 
>     img_patch = transform(img_patch)
> 
>     input_img = img_patch.unsqueeze(0)
> 
>     return input_img
> 
> def plot_3dkeypoints(pred, skeleton):
>     from mpl_toolkits.mplot3d import Axes3D
>     import matplotlib.pyplot as plt
>     import matplotlib as mpl
>     from matplotlib.axes._axes import _log as matplotlib_axes_logger
>     mpl.use("TKAgg", warn=False, force=True)
>     matplotlib_axes_logger.setLevel('ERROR')
> 
>     def set_axes_radius(ax, origin, radius):
>         ax.set_xlim3d([origin[0] - radius, origin[0] + radius])
>         ax.set_ylim3d([origin[1] - radius, origin[1] + radius])
>         ax.set_zlim3d([origin[2] - radius, origin[2] + radius])
> 
>     def set_axes_equal(ax):
>         '''Make axes of 3D plot have equal scale so that spheres appear as spheres,
>         cubes as cubes, etc..  This is one possible solution to Matplotlib's
>         ax.set_aspect('equal') and ax.axis('equal') not working for 3D.
> 
>         Call this function before plt.show()
> 
>         Input
>           ax: a matplotlib axis, e.g., as output from plt.gca().
>         '''
> 
>         limits = np.array([
>             ax.get_xlim3d(),
>             ax.get_ylim3d(),
>             ax.get_zlim3d(),
>         ])
> 
>         origin = np.mean(limits, axis=1)
>         radius = 0.5 * np.max(np.abs(limits[:, 1] - limits[:, 0]))
>         set_axes_radius(ax, origin, radius)
> 
>     fig = plt.figure()
>     ax = fig.add_subplot(111, projection='3d')
> 
>     # Convert from plt 0-1 RGBA colors to 0-255 BGR colors for opencv.
>     cmap = plt.get_cmap('rainbow')
>     colors = [cmap(i) for i in np.linspace(0, 1, len(pred) + 2)]
>     colors = [np.array((c[2], c[1], c[0])) for c in colors]
> 
>     for i, (x, y, z) in enumerate(pred):
>         ax.scatter(x, y, z, c=np.array(colors[i]), marker='o')
> 
>     for (joint_a, joint_b) in skeleton:
>         ax.plot([pred[joint_a][0], pred[joint_b][0]],
>                 [pred[joint_a][1], pred[joint_b][1]],
>                 [pred[joint_a][2], pred[joint_b][2]])
> 
>     ax.set_xlabel('X Label')
>     ax.set_ylabel('Z Label')
>     ax.set_zlabel('Y Label')
>     # The model by default predicts x and z to be the the width-wise and length-wise directions of the original image
>     # With depth added into the y axis. So this rotation shows the original 2D perspective (i.e. the 2D keypoints)
>     ax.view_init(azim=-90, elev=-90)
>     ax.legend()
>     set_axes_equal(ax)
>     plt.show()
> 
> 
> 
> def main():
> 
>     args = parse_args()
>     cfg.set_args(args.gpu_ids)
>     cudnn.fastest = True
>     cudnn.benchmark = True
>     cudnn.deterministic = False
>     cudnn.enabled = True
> 
>     tester = Tester(args.test_epoch)
> 
>     # The pretrained model used is assumed to be  Human36M keypoints and skeleton. Change if a different model is used.
>     tester.joint_num = 18
>     tester.skeleton = (
>         (0, 7), (7, 8), (8, 9), (9, 10), (8, 11), (11, 12), (12, 13), (8, 14), (14, 15), (15, 16), (0, 1), (1, 2), (2, 3),
>         (0, 4), (4, 5), (5, 6))
>     #tester._make_batch_generator()
>     tester._make_model()
> 
>     preds = []
>     with torch.no_grad():
>         itr = 0 # iteration
>         imgpath = "./example_images/2019-06-14_22-19-44_1438_5.png"
>         bbox = (80, 80, 150, 150)
>         input_img = prepare_input(imgpath, bbox)
>         # forward
>         coord_out = tester.model(input_img)
>         print('coord out shape:', coord_out.shape)
> 
>         vis = True
>         if vis:
>             filename = str(itr)
>             tmpimg = input_img[0].cpu().numpy()
>             tmpimg = tmpimg * np.array(cfg.pixel_std).reshape(3,1,1) + np.array(cfg.pixel_mean).reshape(3,1,1)
>             tmpimg = tmpimg.astype(np.uint8)
>             tmpimg = tmpimg[::-1, :, :]
>             tmpimg = np.transpose(tmpimg,(1,2,0)).copy()
>             tmpkps = np.zeros((3,tester.joint_num))
>             tmpkps[:2,:] = coord_out[0,:,:2].cpu().numpy().transpose(1,0) / cfg.output_shape[0] * cfg.input_shape[0]
>             tmpkps[2,:] = 1
>             tmpimg = vis_keypoints(tmpimg, tmpkps, tester.skeleton)
>             cv2.imwrite(filename + '_output.jpg', tmpimg)
>             cv2.imshow('img', tmpimg)
>             cv2.waitKey(0)
>             cv2.destroyAllWindows()
> 
>         coord_out = coord_out.cpu().numpy()
> 
>         vis_3d=True
>         if vis_3d:
>             pred=coord_out.squeeze() #remove first batch dimension
>             plot_3dkeypoints(pred, tester.skeleton)
>         preds.append(coord_out)
>             
>     # evaluate
>     preds = np.concatenate(preds, axis=0)
> 
> 
> if __name__ == "__main__":
>     main()
> ```

do you know how to change the demo code for multi person, here the code is for single one

**Comment by mks0601** [comment]
You can aggregate output from each person by full perspective camera model.

**Comment by mks0601** [comment]
Hi guys, I made a demo code. Please check out https://github.com/mks0601/3DMPPE_POSENET_RELEASE/blob/master/demo/demo.py
