### ISSUE TITLE
How to visualize the 3d skeleton?

### ISSUE THREAD

**Issue by trikim** [mks0601/3DMPPE_POSENET_RELEASE#15]
Hi, thanks for your great work!
I have already got "bbox_root_pose_human36m_output.json" file by run "python test.py --gpu 0 --test_epoch 24". We could get positions(x,y,z) of body joints by parsing "bbox_root_human36m_output.json" and "bbox_root_pose_human36m_output.json". But how to show these infomation in a picture? I am not clear what the [parameters](https://github.com/mks0601/3DMPPE_POSENET_RELEASE/blob/8f62e5b819f1410ab2b8b558a4e4d42ab53b4b19/common/utils/vis.py#L41) (kpt_3d, kpt_3d_vis, kps_lines) under "./common/utils/vis.py" exactly mean. 
`def vis_3d_skeleton(kpt_3d, kpt_3d_vis, kps_lines, filename=None):`

what's more, how to get test result files (preds_2d_kpt_$DB_NAME.mat, preds_3d_kpt_$DB_NAME.mat)? Looking forward to your reply.

**Comment by mks0601** [comment]
`kpt_3d`: 3D coordinates of all body joints
`kpt_3d_vis`': binary flag which indicate this keypoint is valid or invalid (invalid means truncated or not annotated)
`kps_lines`: human body skeleton hiererachy

`preds_2d_kpt_$DB_NAME.mat` can be obtained by running `test.py` of this repo.

**Comment by trikim** [comment]
@mks0601 
Thank you very much!
I have generated the 3D visual picture. Could you give me some advices about adding one 2D image to one plane(such as plane z=0) in 3D space?
![3D_vis](https://user-images.githubusercontent.com/26160520/65735626-a6732f80-e10a-11e9-8c14-6a54c61c886c.png)

I could not obtain preds_2d_kpt_$DB_NAME.mat by running test.py. Maybe I should modify some parameters. Thanks again!

**Comment by Yxiaoqian** [comment]
> @mks0601
> Thank you very much!
> I have generated the 3D visual picture. Could you give me some advices about adding one 2D image to one plane(such as plane z=0) in 3D space?
> ![3D_vis](https://user-images.githubusercontent.com/26160520/65735626-a6732f80-e10a-11e9-8c14-6a54c61c886c.png)
> 
> I could not obtain preds_2d_kpt_$DB_NAME.mat by running test.py. Maybe I should modify some parameters. Thanks again!

can you give me some advice to visualize the result like your?
 thank you very much!

**Comment by mks0601** [comment]
Hi, I used matlab to do that.
You can see matlab scripts at `vis` folder. Thanks!

**Comment by henryyuanheng-wang** [comment]
Thank you so much for you amazing work! @mks0601 

I've got preds_2d_kpt_$DB_NAME.mat, preds_3d_kpt_$DB_NAME.mat by running test.py and trying to do some visualization. Wondering where do I get kpt_3d, kpt_3d_vis, kps_lines? I'm assuming kpt_3d can be obtained from preds_3d_kpt_$DB_NAME.mat. Can you point me to some directions on getting kpt_3d_vis and kps_lines?

**Comment by SkyJoyTianle** [comment]
> Thank you so much for you amazing work! @mks0601
> 
> I've got preds_2d_kpt_$DB_NAME.mat, preds_3d_kpt_$DB_NAME.mat by running test.py and trying to do some visualization. Wondering where do I get kpt_3d, kpt_3d_vis, kps_lines? I'm assuming kpt_3d can be obtained from preds_3d_kpt_$DB_NAME.mat. Can you point me to some directions on getting kpt_3d_vis and kps_lines?



> @mks0601
> Thank you very much!
> I have generated the 3D visual picture. Could you give me some advices about adding one 2D image to one plane(such as plane z=0) in 3D space?
> ![3D_vis](https://user-images.githubusercontent.com/26160520/65735626-a6732f80-e10a-11e9-8c14-6a54c61c886c.png)
> 
> I could not obtain preds_2d_kpt_$DB_NAME.mat by running test.py. Maybe I should modify some parameters. Thanks again!

你知道怎么用matlab弄出图像吗，我这边一直显示字段不对，然后载入不了那两个文件

**Comment by mks0601** [comment]
@henryyuanheng-wang  sorry for late reply. I think this [line](https://github.com/mks0601/3DMPPE_POSENET_RELEASE/blob/7df62e283ddc13303f0c4cf3fbd318dd5466eea6/main/test.py#L71) would be helpful.
