### ISSUE TITLE
Camera parameters

### ISSUE THREAD

**Issue by edrdos101** [mks0601/3DMPPE_POSENET_RELEASE#16]
I noticed that you have two repositories with seemingly similar implementation but one with visualisation code and the other without. However, in no-vis code the model takes camera parameters as input, could you explain why the difference?

Also, could you explain how important camera parameters are for accuracy of the model?

Thanks!

**Comment by mks0601** [comment]
[This repo](https://github.com/mks0601/3DMPPE_ROOTNET_RELEASE) contains RootNet part of my [paper](https://arxiv.org/abs/1907.11346). The RootNet estimates absolute distance between camera and human root joint (e.g., Pelvis). This repo contains PoseNet of my [paper](https://arxiv.org/abs/1907.11346). The PoseNet estimates root-relative 3D human pose. For more detail, please read my paper.
