### ISSUE TITLE
where is mpii_mupots_config?

### ISSUE THREAD

**Issue by surelyee** [mks0601/3DMPPE_POSENET_RELEASE#17]
hello~,where is mpii_mupots_config file?  

mpii_mupots_config is code in mpii_mupots_multiperson_eval.m, maybe mpii_mupots_config is a .m file, when i run the mpii_mupots_multiperson_eval.m, it will be wrong.

thanks!

**Comment by mks0601** [comment]
You can download at [here](http://gvv.mpi-inf.mpg.de/projects/SingleShotMultiPerson/)

**Comment by surelyee** [comment]
@mks0601 thanks for your reply, i have some other questions.
Do you calculate x and y using absolute z in posenet? why not use your estamated z by rootnet?
thanks.

**Comment by mks0601** [comment]
Could you clarify your question? Which x and y do you mean?

**Comment by surelyee** [comment]
@mks0601 sorry, i mean that x and y is absolute x and y in camera, it maybe need a absolute z to compute. and i  just recently read your paper, and find it.
![image](https://user-images.githubusercontent.com/24806238/66382593-124c7680-e9ee-11e9-8277-23218f33ef18.png)

![image](https://user-images.githubusercontent.com/24806238/66382796-60fa1080-e9ee-11e9-8309-dfddb26febe0.png)

Dose your 3DPCK(abs) means that you use your rootnet get a estamated z ( the center_cam[:,2])?
and when use rootnet get 31.6 result?
and i can't find the code of  computing the  3DPCK(abs)

**Comment by mks0601** [comment]
I cannot understand what you are asking... Please clarify your question with correct sentence.. 
3DPCK_{abs} can  be computed from `data/MuPoTS/mpii_mupots_multiperson_eval.m` by setting `is_relative` false.

**Comment by surelyee** [comment]
@mks0601 ok，thanks, i have solved the problem.
