### ISSUE TITLE
Running it without GPU on cluster

### ISSUE THREAD

**Issue by nshreyasvi** [mks0601/3DMPPE_POSENET_RELEASE#18]
Hello,
I wanted to run this system on a HPC cluster without adding arguments for GPU. Is there a way to do it?

**Comment by nshreyasvi** [comment]
Hello,
It is a high performance computing cluster. Will it be possible to remove the arguments and run it?

**Comment by mks0601** [comment]
If you change `set_args` in `config.py` and `parse_args` in `train.py` and `test.py`, you can write new GPU assignment code.
