### ISSUE TITLE
MSCOCO dataset download link

### ISSUE THREAD

**Issue by ShuangjunLiu** [mks0601/3DMPPE_POSENET_RELEASE#19]
Hello,  can you provides the link for MSCOCO dataset?  

Even if images and annotations are from [coco2017](http://cocodataset.org/#download), 
I think the "bbox" link is still missing. 

Thanks.

**Comment by mks0601** [comment]
What do you mean by 'provide the link for MSCOCO dataset'?
The bbox is calculated in `data/$DB_NAME/$DB_NAME.py`.

**Comment by ShuangjunLiu** [comment]
Oh, I see.
