### ISSUE TITLE
Question about dataset generation

### ISSUE THREAD

**Issue by sdxass** [mks0601/3DMPPE_POSENET_RELEASE#2]
Hi,

Sorry to brother you again. I have another question: How did you generate the processed MuCO-3DHP dataset? Did you use the official MATLAB code to generate these data? I tried their code, but the quality of generated data are worse than yours.

**Comment by mks0601** [comment]
Yes I used their matlab code. what do you mean by quality? I think I didn't do special things.

**Comment by sdxass** [comment]
Thank you for your response! I mean images generated by myself are inferior. 

I just tried to use some images as background to re-generate the multi-person dataset using official matlab code. It seems like the new generated images are similar to yours. And now my problem is solved.

![000586](https://user-images.githubusercontent.com/20400805/62535540-3e2c6e00-b87e-11e9-91ee-0a704bc3a712.jpg)
![000158](https://user-images.githubusercontent.com/20400805/62535491-2228cc80-b87e-11e9-8213-e9db51cb28a4.jpg)
