### ISSUE TITLE
Is the order of data changed in MuPoTS when I select the "use_gt_bbox" mode?

### ISSUE THREAD

**Issue by li19960612** [mks0601/3DMPPE_POSENET_RELEASE#21]
Hello! I want to evaluate my modified PoseNet with 3DPCK in MuPoTS, it needs to be saved into .mat and evaluate in Matlab. When I select the "use_gt_bbox" mode, the results are very bad. If I evaluate the mpjpe directly, it seems to have a good result. Is there any changing, missing or Python-Matlab-mismatch with "use_gt_bbox" in MuPoTS data?

**Comment by mks0601** [comment]
Hmm.. The python and matlab codes are completely separated. Did you get bad result only when "use_gt_bbox" is enabled and get good result when it is disabled?
