### ISSUE TITLE
 bbox should be aspect ratio preserved-extended. It is done in RootNet.

### ISSUE THREAD

**Issue by jieluyan** [mks0601/3DMPPE_POSENET_RELEASE#22]
rootNet) lulu@IoTLab-002:~/git-hub-packages/POSENET/main$ python test.py --gpu 0-4 --test_epoch 24
>>> Using GPU: 0,1,2,3,4
11-03 05:13:40 Creating dataset...
creating index...
index created!
Get bounding box and root from ../data/Human36M/bbox_root/bbox_root_human36m_output.json
Traceback (most recent call last):
  File "test.py", line 82, in <module>
    main()
  File "test.py", line 41, in main
    tester._make_batch_generator()
  File "/home/lulu/git-hub-packages/POSENET/main/../common/base.py", line 136, in _make_batch_generator
    testset = eval(cfg.testset)("test")
  File "/home/lulu/git-hub-packages/POSENET/main/../data/Human36M/Human36M.py", line 31, in __init__
    self.data = self.load_data()
  File "/home/lulu/git-hub-packages/POSENET/main/../data/Human36M/Human36M.py", line 118, in load_data
    bbox = bbox_root_result[str(image_id)]['bbox'] # bbox should be aspect ratio preserved-extended. It is done in RootNet.
KeyError: '1559752'

**Comment by mks0601** [comment]
Did you check which protocol to use?

**Comment by jieluyan** [comment]
yes, I use protocol1

**Comment by mks0601** [comment]
I mean did you prepare bbox_root_human36m_output.json of your protocol?

**Comment by jieluyan** [comment]
Yes, I prepared that json file. Now I fixed it by changing the human3.6M json file from protocol 1 to protocal 2 and also change the pre-trained model to protocol 2, and now the problem was fixed. It seems like there's something wrong in the protocol 1 (two json files or the pre trained model).

thank you very much for your helping. and below is the new rs using protocol 2

(rootNet) lulu@IoTLab-002:~/git-hub-packages/POSENET/main$ python test.py --gpu 0-7 --test_epoch 24
>>> Using GPU: 0,1,2,3,4,5,6,7
11-04 02:57:48 Creating dataset...
creating index...
index created!
Get bounding box and root from ../data/Human36M/bbox_root/bbox_root_human36m_output.json
11-04 02:59:03 Load checkpoint from /home/lulu/git-hub-packages/POSENET/main/../output/model_dump/snapshot_24.pth.tar
11-04 02:59:03 Creating graph...
100%|██████████████████████████████████████████████████████████████████████████████████| 68/68 [01:37<00:00,  1.43s/it]
Evaluation start...
Test result is saved at /home/lulu/git-hub-packages/POSENET/main/../output/result/bbox_root_pose_human36m_output.json
creating index...
index created!
Protocol #1 error (PA MPJPE) >> tot: 41.38
Directions: 37.28 Discussion: 41.04 Eating: 41.30 Greeting: 39.85 Phoning: 42.06 Posing: 35.30 Purchases: 37.06 Sitting: 51.49 SittingDown: 56.49 Smoking: 41.92 Photo: 42.99 Waiting: 37.65 Walking: 31.04 WalkDog: 41.46 WalkTogether: 36.41 

Protocol #2 error (MPJPE) >> tot: 54.57
Directions: 51.17 Discussion: 56.86 Eating: 51.34 Greeting: 51.92 Phoning: 56.62 Posing: 47.53 Purchases: 50.51 Sitting: 64.74 SittingDown: 68.81 Smoking: 55.09 Photo: 56.98 Waiting: 50.40 Walking: 42.26 WalkDog: 56.54 WalkTogether: 47.48
