### ISSUE TITLE
I cannot get preds_2d_kpt_$DB_NAME.mat, preds_3d_kpt_$DB_NAME.mat

### ISSUE THREAD

**Issue by Yxiaoqian** [mks0601/3DMPPE_POSENET_RELEASE#23]
After I run the test.py of this repo, I cannot get the 'preds_2d_kpt_$DB_NAME.mat', 'preds_3d_kpt_$DB_NAME.mat', but only the 'bbox_root_pose_human36m_output.json' ?

**Comment by mks0601** [comment]
`preds_2d_kpt_$DB_NAME.mat` and `preds_3d_kpt_$DB_NAME.mat` are produced only when you test on `MSCOCO` or `MuPoTS` dataset.  did not implemented visualization function for `H36M` dataset.

**Comment by Yxiaoqian** [comment]
ok, thanks for your quickly reply.
