### ISSUE TITLE
Where is the MuPoTS (MultiPersonTestSet) dataset? Only found mupots-3d-eval.zip

### ISSUE THREAD

**Issue by banana16314** [mks0601/3DMPPE_POSENET_RELEASE#25]
Thanks for your work! 
I like your code style, man!
My question is as the title. I only found the file _mupots-3d-eval.zip_

**Comment by mks0601** [comment]
Hi! Thanks!
You can download MuPoTS dataset at [here](http://gvv.mpi-inf.mpg.de/projects/SingleShotMultiPerson/)

**Comment by banana16314** [comment]
Thanks for your reply!
I opened the link. 
Is _MuPoTS-3D Dataset ZIP, 10 KB_ the MuPoTS dataset? 
I am surprised by the size - 10kb.
Now the directory structure of mine:
|       |-- data
|       |   |-- MultiPersonTestSet
                |-- mupots-3d-eval
                    |-- util
                    | `-- mpii_mupots_multiperson_eval.m
|       |   `-- MuPoTS-3D.json
It is all right?

**Comment by mks0601** [comment]
You should run some scripts to download the dataset. The 10KB is for some scripts.

**Comment by banana16314** [comment]
Yep!
There is a bash file named _get_mupots-3d.sh_
`#!/bin/bash
echo "Please ensure you have about 6GB free. Uncomment the lines below to proceed with downloading the dataset" >&2
#source_path="http://gvv.mpi-inf.mpg.de/projects/SingleShotMultiPerson"
#if [ ! -f "./MultiPersonTestSet.zip" ]; then
#  wget "$source_path/MultiPersonTestSet.zip"  
#fi`
I just run the command: _wget -c http://gvv.mpi-inf.mpg.de/projects/SingleShotMultiPerson/MultiPersonTestSet.zip_
Thanks!
