### ISSUE TITLE
normalization

### ISSUE THREAD

**Issue by GUO-W** [mks0601/3DMPPE_POSENET_RELEASE#26]
Hello,

Thanks for your great work!

I would like to ask why do you set the mean and std to a fixed number, and how did you get the numbers of:
    pixel_mean = (0.485, 0.456, 0.406)
    pixel_std = (0.229, 0.224, 0.225)
in cfg ?

Thanks a lot!

**Comment by mks0601** [comment]
They are from imagenet dataset. I didn't calculate, but get it from some other article.

**Comment by GUO-W** [comment]
OK, thanks for your reply~
