### ISSUE TITLE
Cannot download dataset files from the google drive quickly

### ISSUE THREAD

**Issue by karenyun** [mks0601/3DMPPE_POSENET_RELEASE#28]
Hi, the dataset files are too large and could not download from the google drive. Do you have any other links that can access?

**Comment by mks0601** [comment]
Thanks for reporting. I'm splitting the zipped dataset into 20GB chunks. Will be available soon.

**Comment by karenyun** [comment]
Many Thanks~~

**Comment by mks0601** [comment]
I replaced H36M dataset to splitted ones. Also, I'm uploading MuCo-3DHP splitted data. Will be available soon. Thanks!

**Comment by karenyun** [comment]
Hi, sorry the split files are still too large which exceed the download limitation, could you make it a bit smaller? Sorry to bother.

**Comment by mks0601** [comment]
What is your download limitation?

**Comment by karenyun** [comment]
I google the reason, finding that "If a large number of users downloaded a file, the file may be blocked for a period of time. The reason being Google wants to minimize abuse", anyway I cannot download any split files now?

**Comment by karenyun** [comment]
Oh, now it can download, thanks very much!

**Comment by karenyun** [comment]
Hi, when unzipping the images.tar.gzab and so on encounter an issue, as the following:

**tar -zxvf images.tar.gzab

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now**

Or 
**tar -xf images.tar.gzab 
tar: This does not look like a tar archive
tar: Skipping to next header
tar: Archive contains ‘s\367фF\3157̄-\r\a’ where numeric off_t value expected
tar: Archive contains ‘\2341"\036\202\275|8\370T=\230’ where numeric off_t value expected
tar: Archive contains ‘\352<xߏ\376\242\275F41\216’ where numeric off_t value expected
tar: Archive contains ‘\364\277\036\\\357\230\303S\265\311\031\003’ where numeric off_t value expected**
While the images.tar.gzaa file can be zipped successfully? Do you use a different zip way?

**Comment by mks0601** [comment]
Try
`cat images.tar.gz* | tar -zxvpf -`

**Comment by karenyun** [comment]
Thanks so much!

**Comment by KarlosMuradyan** [comment]
Hi @mks0601 . I'm having trouble extracting MuCo-3DHP dataset. I've tried to extract `augmented_set.tar.gzab` and `augmented_set.tar.gzae` files with the shell script  `extract_targz.sh`. All files has been downloaded from [this link](https://drive.google.com/drive/folders/1RO1d-_dAggOMkAosgVEeNAw4x5i_-vAF).

I'm using latest `tar` version, which is `1.32`.

The error message is the following:

```
gzip: stdin: not in gzip format
tar: Child died with signal 13
tar: Error is not recoverable: exiting now
```

I tried also manually running script `cat augmented_set.tar.gz* | tar -zxvpf -`, which gave the same error message.

**Comment by KarlosMuradyan** [comment]
On the other hand, unaugmented data extracts as expected.

**Comment by mks0601** [comment]
Hmm.. could you see this [link](https://askubuntu.com/a/1082295) and run other command?

**Comment by Learningm** [comment]
Hi, i get the same error when i type **cat images.tar.gz* | tar -zxvpf -**  to extract human3.6m dataset images.
cat images.tar.gz* | tar -zxvpf -

gzip: stdin: not in gzip format
tar: Child died with signal 13
tar: Error is not recoverable: exiting now

How can i solve it? Thanks!

**Comment by mks0601** [comment]
hmm could you remove 'z'?
cat images.tar.gz* | tar -xvpf -

**Comment by Learningm** [comment]
> hmm could you remove 'z'?
> cat images.tar.gz* | tar -xvpf -

> hmm could you remove 'z'?
> cat images.tar.gz* | tar -xvpf -

yes, i did. But i got some similar errors like the above one, it's confusing.
cat images.tar.gz* | tar -xvpf -
tar: This does not look like a tar archive
tar: Skipping to next header
tar: Archive contains ‘|\277\2711\244\250\370۷<\373\212’ where numeric off_t value expected
tar: Exiting with failure status due to previous errors

**Comment by Learningm** [comment]
> hmm could you remove 'z'?
> cat images.tar.gz* | tar -xvpf -

yes, i did. But i got some similar errors like the above one, it's confusing.
cat images.tar.gz* | tar -xvpf -
tar: This does not look like a tar archive
tar: Skipping to next header
tar: Archive contains ‘|\277\2711\244\250\370۷<\373\212’ where numeric off_t value expected
tar: Exiting with failure status due to previous errors

**Comment by mks0601** [comment]
Weird.. cat images.tar.gz* | tar -zxvpf - works well for me.
Are you sure you downloaded all files without corruption?

**Comment by mks0601** [comment]
Could you try this one? https://askubuntu.com/questions/1179657/how-to-extract-tgz-part

**Comment by pengyuwang35** [comment]
> > hmm could you remove 'z'?
> > cat images.tar.gz* | tar -xvpf -
> 
> yes, i did. But i got some similar errors like the above one, it's confusing.
> cat images.tar.gz* | tar -xvpf -
> tar: This does not look like a tar archive
> tar: Skipping to next header
> tar: Archive contains ‘|\277\2711\244\250\370۷<\373\212’ where numeric off_t value expected
> tar: Exiting with failure status due to previous errors

I met the same problem, have you solved the problem?

**Comment by pengyuwang35** [comment]
> On the other hand, unaugmented data extracts as expected (I tried `unaugmented_set.tar.gzaa` only for now).

I met the same problem, have you solved the problem?

**Comment by Learningm** [comment]
> > > hmm could you remove 'z'?
> > > cat images.tar.gz* | tar -xvpf -
> > 
> > 
> > yes, i did. But i got some similar errors like the above one, it's confusing.
> > cat images.tar.gz* | tar -xvpf -
> > tar: This does not look like a tar archive
> > tar: Skipping to next header
> > tar: Archive contains ‘|\277\2711\244\250\370۷<\373\212’ where numeric off_t value expected
> > tar: Exiting with failure status due to previous errors
> 
> I met the same problem, have you solved the problem?

Not solved yet.

**Comment by mks0601** [comment]
Please check md5sum.
https://docs.google.com/document/d/1lqnkXek4_bibyK0tbDaCPOG905kfb0zKYc8aqN4EX4o/edit?usp=sharing

**Comment by JonathanLehner** [comment]
the md5sum is correct but there is still the no gzip error

**Comment by mks0601** [comment]
Did you run `sh extract_targz.sh`?

**Comment by JonathanLehner** [comment]
yes

**Comment by JonathanLehner** [comment]
I ran sh extract_targz.sh

**Comment by JonathanLehner** [comment]
I also tried updating gzip and tar but I have the latest versions. I used Ubuntu 20.02. File *.tar.* gives "file: data". Some of the files could be extracted but most have the error:
gzip: stdin: not in gzip format
tar: Child died with signal 13
tar: Error is not recoverable: exiting now

**Comment by JonathanLehner** [comment]
did you try downloading and decompressing yourself? maybe the files got modified by google during upload

**Comment by JonathanLehner** [comment]
on Google drive it only shows gzaa as archive too
