### ISSUE TITLE
No RootNet Part

### ISSUE THREAD

**Issue by karenyun** [mks0601/3DMPPE_POSENET_RELEASE#29]
Hi, the network seems not to contain RootNet part, sorry I did not find the network to predict \gamma and K for computing the camera-space root depth as described in the paper? Could give some advice?

**Comment by mks0601** [comment]
You can see here
https://github.com/mks0601/3DMPPE_ROOTNET_RELEASE

**Comment by karenyun** [comment]
Oh, thanks for your quick reply!
