### ISSUE TITLE
ModuleNotFoundError: No module named 'dataset'

### ISSUE THREAD

**Issue by wangzheallen** [mks0601/3DMPPE_POSENET_RELEASE#3]
When I ran `python train.py --gpu 0-1`, it says: ModuleNotFoundError: No module named 'dataset'

**Comment by wangzheallen** [comment]
seems  Root_repository has one but not sure whether it applies to this repo or not.

**Comment by mks0601** [comment]
Sorry I think I forgot to upload that file. Now, I uploaded!
