### ISSUE TITLE
Some problem of Human36 dataset.......

### ISSUE THREAD

**Issue by guoyage** [mks0601/3DMPPE_POSENET_RELEASE#31]
Hello, first of all, thank you for your wonderful research, but I found that the download link for the Human36 dataset you provided is broken. Could you please provide a new download address code? thank you very much!!!!!!

**Comment by mks0601** [comment]
You cannot access to google drive link? All links are replaced with google drive links several weeks ago.

**Comment by guoyage** [comment]
Not Found
The requested URL was not found on this server.
Apache/2.4.41 (Ubuntu) Server at cv.snu.ac.kr Port 443

When I open the URL, I get this error...

**Comment by mks0601** [comment]
Could you refresh and empty the cached ones? That link is expired and maybe your browser cached some old links.

**Comment by guoyage** [comment]
> Could you refresh and empty the cached ones? That link is expired and maybe your browser cached some old links.

Thank you for your immediate answer, but when I use 
wget https://cv.snu.ac.kr/dataset/3DMPPE/Human36M/images.zip command to download the file, I get this erro:

已发出 HTTP 请求，正在等待回应... 404 Not Found
2019-12-27 12:12:22 错误 404：Not Found。

 Is the download link changed?   thanks

**Comment by mks0601** [comment]
Again, that link is broken. The correct one is 
https://drive.google.com/drive/folders/1kgVH-GugrLoc9XyvP6nRoaFpw3TmM5xK?usp=sharing

Again, all links are replaced with google drive links.

**Comment by mks0601** [comment]
All links in README are already replaced with new links. You should refresh and empty caches.

**Comment by guoyage** [comment]
I'm really sorry to trouble you many times, but when I use Google Cloud Disk to download a file, the download limit appears, and the content is probably: Downloading this file will exceed the download limit, so it cannot be downloaded at this time.

**Comment by mks0601** [comment]
Some people suffered from that problem.. I found a simple solution but it requires your google drive account has more than 20GB free storage. Could you add each splitted `tar.gz` files to your google drive account by making copy and download?

**Comment by mks0601** [comment]
My personal google drive account also suffered from the problem exactly same with yours, but I solved the problem with this simple trick. I think this is because many people tried to download this dataset so that it exceeds the google drive download limit (maybe 750GB?).

**Comment by mks0601** [comment]
I added some instructions for this problem in README. Thanks for reporting!
