### ISSUE TITLE
The difference between your model and sun?

### ISSUE THREAD

**Issue by surelyee** [mks0601/3DMPPE_POSENET_RELEASE#32]
Any difference between your model and sun?（in eccv2018，Integral Human Pose Regression）
thanks.

**Comment by Sadegh28** [comment]
As I know, that work is for single human pose estimation, but this is for multi-human pose estimation.

**Comment by mks0601** [comment]
The PoseNet is similar, but RootNet is a newly designed one. It can estimate the distance between camera and human root joint in a camera-intrinsic normalized space.

Here is RootNet repo: https://github.com/mks0601/3DMPPE_ROOTNET_RELEASE

**Comment by surelyee** [comment]
> The PoseNet is similar, but RootNet is a newly designed one. It can estimate the distance between camera and human root joint in a camera-intrinsic normalized space.
> 
> Here is RootNet repo: https://github.com/mks0601/3DMPPE_ROOTNET_RELEASE

thanks for your reply
