### ISSUE TITLE
Human36m Protocol 2 error (MPJPE) >> tot: 74.17, which is much larger than 53.3 in the paper

### ISSUE THREAD

**Issue by banana16314** [mks0601/3DMPPE_POSENET_RELEASE#34]
Hi, i followed your instruction and retrained the posenet, but the result of human36m protocol 2 was not the same as the table 4 in the paper. here is my result:
_>>> Using GPU: 0
01-08 04:44:22 Creating dataset...
Load data of H36M Protocol 2
creating index...
index created!
Get bounding box and root from groundtruth
01-08 04:44:38 Load checkpoint from /home/***/3DMPPE_POSENET_RELEASE/main/../output/model_dump/snapshot_24.pth.tar
01-08 04:44:38 Creating graph...
100% 272/272 [01:09<00:00,  2.02it/s]
Evaluation start...
Protocol 2 error (MPJPE) >> tot: 74.17
Directions: 67.14 Discussion: 79.61 Eating: 64.75 Greeting: 67.06 Phoning: 71.20 Posing: 65.54 Purchases: 71.40 Sitting: 92.58 SittingDown: 109.11 Smoking: 73.97 Photo: 80.40 Waiting: 72.86 Walking: 52.37 WalkDog: 73.72 WalkTogether: 57.12_ 
can you help me? what shall i do if i wanna train the posenet and get a similar MPJPE (53.3)?
Thank you very much!

**Comment by mks0601** [comment]
Did you use both H36M and MPII as teaining set? As described in the paper, that result is from a model trained on both H36M and MPII. You should set trainset in main/config.py as [Human36M, MPII]

**Comment by banana16314** [comment]
Thanks for your reply!
in main/config.py:
    _#trainset = ['Human36M']   

    trainset = ['Human36M', 'MPII']_  
is it right?

**Comment by mks0601** [comment]
Correct. I should've set the trainset to include MPII also 😂

**Comment by banana16314** [comment]
Thanks! 
i will try it again!
so nice you are!
