### ISSUE TITLE
Run on one random image

### ISSUE THREAD

**Issue by zhangy76** [mks0601/3DMPPE_POSENET_RELEASE#36]
Thanks for the great work! I wonder how to test the code on one specfic image?

**Comment by ds862** [comment]
Do you know how to do it？

**Comment by mks0601** [comment]
You can make a new `data/DB/DB.py` following that of other datasets and `.son` file in COCO format.
To make the `.json` file, you can follow this [code](https://github.com/mks0601/TF-SimpleHumanPose/blob/master/tool/posetrack2coco.py).

**Comment by thimhh** [comment]
I implemented to read a single image and even visualization from webcam livestream on a Jetson Nano. But it's real quick and dirty code... Perhaps I have some time later this week to create a pull request but I am not sure if things like that should be in this repo here.

**Comment by mks0601** [comment]
Oh that is good. Could you create a pull request? I'll check the code and try to make it merged.

**Comment by lucas-amin** [comment]
I would love to know that too.

I`m trying to convert a single numpy array image to the model tensor input format, but still without success tough...

**Comment by mks0601** [comment]
I'll make a demo code soon

**Comment by thimhh** [comment]
Sorry guys, I had no time to clean up my code for a pull request, but here some snippets from my code, this is basically put into the middle of the current test.py file and you need of course some additional imports. At the end you can do with the 3d data whatever you want. I simply write it directly to a local 3d matplotlib to have local visualization or in the other case I simply open a UDP socket and send the coord_out to another device where I visualize it in the same way. You could even use the 2d-"vis" from the test.py file. An I removed all the evaluation stuff at the end of the file since I don't need it for my test.

I hope I didn't miss anything...

**Read from WebCam** 

```
            cam = VideoCapture(0)
            from PIL import Image
            from torchvision import transforms
                
            dim = (256, 256)

            with torch.no_grad():
                for camx in range (1, 100000):

                    s, img = cam.read()

                    img = cv2.resize(img, dim, interpolation = cv2.INTER_AREA)
                    image = np.asarray(img)
                    img_height, img_width, img_channels = image.shape
                    for i in range (img_channels):
                        image[:, :, i] = np.clip(image[:, :, i] * 1, 0, 255)
                    image = image[:,:,::-1].copy()
                    image = image.astype(np.float32)
                    data_transforms = transforms.Compose([
                        #transforms.RandomResizedCrop(256),
                        transforms.ToTensor(),
                        transforms.Normalize(mean=cfg.pixel_mean, std=cfg.pixel_std)
                        ])
                    image = data_transforms(image)

                    #Convert to 4-D from 3-D image
                    image = image.unsqueeze(0)
                    
                    coord_out = tester.model(image)
                    print (str(coord_out))

```
**Read from file**

```
    with torch.no_grad():
            from PIL import Image
            from torchvision import transforms
            img_path="t1.jpg"
            image = cv2.imread(img_path, cv2.IMREAD_COLOR | cv2.IMREAD_IGNORE_ORIENTATION)
            img_height, img_width, img_channels = image.shape
            for i in range (img_channels):
                image[:, :, i] = np.clip(image[:, :, i] * 1, 0, 255)
            image = image[:,:,::-1].copy()
            image = image.astype(np.float32)
            data_transforms = transforms.Compose([
                #transforms.RandomResizedCrop(256),
                transforms.ToTensor(),
                transforms.Normalize(mean=cfg.pixel_mean, std=cfg.pixel_std)
                ])
            image = data_transforms(image)
            #Convert to 4-D from 3-D image
            image = image.unsqueeze(0)

            coord_out = tester.model(image)
            print (str(coord_out))
```

**Comment by mks0601** [comment]
Great thanks! I'll make a demo code using your snippets.
Again, thanks!

**Comment by thimhh** [comment]
And for anyone using a webcam: With a Jetson Nano I don't get more than 3-4 fps. Due to that when I read from my webcam there seems to be a buffer with older images. So I got always a very old picture which led to a "lag" of 1-2 seconds. I did a bad workaround and wrote a separate thread started which reads continuously from  the webcam so I have always the latest picture when my code from above grabs a new image from the cam. This might be different from cam to cam. I hope I'll have some time to test it with  a Basler MIPI-CSI camera in the near future which should give me better options, especially no resize and better image quality since it has a proper ISP built in and no lag issue.

**Comment by lucas-amin** [comment]
Hello! I've worked on top @thimhh code, and managed to run on webcam with 2d visualization. Now I'm trying to visualize 3d results and deal with confidence score along each skeleton node.

Please, if you find better ways to code this or visualize 3d results or confidence score, It would help a lot!

Here is the full script:

    from torchvision import transforms
    import argparse
    import numpy as np
    import cv2
    from config import cfg
    import torch
    from base import Tester
    import torch.backends.cudnn as cudnn
    from utils.vis import vis_keypoints
    from common.utils.vis import vis_3d_skeleton

    def parse_args():
        parser = argparse.ArgumentParser()
        parser.add_argument('--gpu', type=str, dest='gpu_ids', default='0')
        parser.add_argument('--test_epoch', type=str, dest='test_epoch', default=24)
        args = parser.parse_args()
    
        # test gpus
        if not args.gpu_ids:
            assert 0, print("Please set proper gpu ids")
    
        assert args.test_epoch, 'Test epoch is required.'
    
        return args
    
    
    cam = cv2.VideoCapture(0)
    
    dim = (256, 256)
    
    args = parse_args()
    cfg.set_args(args.gpu_ids)
    cudnn.fastest = True
    cudnn.benchmark = True
    cudnn.deterministic = False
    cudnn.enabled = True
    
    tester = Tester(args.test_epoch)
    tester._make_batch_generator()
    tester._make_model()
    
    with torch.no_grad():
        for camx in range(1, 100000):
    
            s, original_image = cam.read()
    
            original_image = cv2.resize(original_image, dim, interpolation=cv2.INTER_AREA)
            image = np.asarray(original_image)
            img_height, img_width, img_channels = image.shape
            for i in range(img_channels):
                image[:, :, i] = np.clip(image[:, :, i] * 1, 0, 255)
            image = image[:, :, ::-1].copy()
            image = image.astype(np.float32)
    
            data_transforms = transforms.Compose([
                # transforms.RandomResizedCrop(256),
                transforms.ToTensor(),
                transforms.Normalize(mean=cfg.pixel_mean, std=cfg.pixel_std)
            ])
    
            image_tensor = data_transforms(image)
    
            # Convert to 4-D from 3-D image
            image_tensor = image_tensor.unsqueeze(0)
    
            coord_out = tester.model(image_tensor)
            tensors = list(coord_out.data[0])
    
            vis_2d = True
            # Working 2d visualization
            if vis_2d:
                keypoints = np.zeros((3, tester.joint_num))
                keypoints[:2, :] = coord_out[0, :, :2].cpu().numpy().transpose(1, 0) / cfg.output_shape[0] * \
                                   cfg.input_shape[0]
                keypoints[2, :] = 1
                tmpimg = vis_keypoints(original_image, keypoints, tester.skeleton)
    
            # Not working 3d visualization
            if not vis_2d:
                keypoints = np.zeros((3, tester.joint_num))
                keypoints[:2, :] = coord_out[0, :, :2].cpu().numpy().transpose(1, 0) / cfg.output_shape[0] * \
                                   cfg.input_shape[0]
                keypoints[2, :] = 1
                keypoints = keypoints.transpose()
    
                tmpimg = vis_3d_skeleton(original_image, keypoints, tester.skeleton)
    
            cv2.imshow("window", tmpimg)
            cv2.waitKey(1)

**Comment by debarundhar** [comment]
Are the pre-trained models provided [here](https://drive.google.com/drive/folders/1UOfSrC2_PGkBXALP3pda5sYqRoG7eFxF?usp=sharing) up-to-date? I seem to be getting pretty much the same pose (using code similar to those seen above) no matter what image I use as input. 
![sample_2d_pose](https://user-images.githubusercontent.com/9699976/76676945-f81b5380-659e-11ea-99cc-40215c0f282f.png)
![sample_2d_pose_2](https://user-images.githubusercontent.com/9699976/76676947-fa7dad80-659e-11ea-8471-9c0b4dff9ea2.png)

**Comment by mks0601** [comment]
Yes they are up-to-date and I have no problem like yours. What is your pytorch version? I found that in lower version, batch normalization does not work well.

**Comment by mks0601** [comment]
Awesome @lucas-amin

**Comment by debarundhar** [comment]
@mks0601 I'm running the latest Pytorch v1.4.0. 

The problem was not due to the version though, but rather due to my confusion around the expected pixel value range. Since your config shows you using `pixel_mean = (0.485, 0.456, 0.406)` and `pixel_std = (0.229, 0.224, 0.225)` for normalization, I assumed your model expected pixel values to range from 0-1. When I changed it back to 0-255, the model works as expected.

**Comment by mks0601** [comment]
Yes actually that is my mistake :( I should've been fixed that mistake before training models, but all models are already trained from that code

**Comment by amirrezahesamian** [comment]
@mks0601 Thank you for the great work.
I've been working to implement your code on video frames and visualize 3D and 2D results. And after visualization 3D positions of each person were quite erratic while the 2D projections of the 3D poses look good, It looks like they are affected by a large 3D error in different frames.
I would like to ask your opinion about what would be the possible problems in this situation.

**Comment by mks0601** [comment]
Which 3D pose did you visualize? The x- and y- axis coordinates are image coordinates (pixel unit) or camera-centered coordinates (mm unit)?

**Comment by amirrezahesamian** [comment]
Thank you for your response.
I visualized data in MuPoTS format and x- and y-axis coordinates are camera-centered coordinates as in the "MuPoTS.py" file, pixel2cam function is used to back project image coordinates to camera coordinate system.
I am looking to have animation results like on the main page of this repository.

**Comment by mks0601** [comment]
Did you visualize absolute 3D pose (preds_3d_kpt_mupots.mat)? Then, I think root joint-relative 3D pose might be good, but absolute 3D pose might be erratic because of the estimation error of the RootNet (absolute depth of the root joint). The preds_3d_kkpt_mupots.mat file contains absolute 3D pose (estimation of PoseNet + estimation of RootNet).

**Comment by mks0601** [comment]
There can be estimation errors of the RootNet because it is quite hard to predict robust absolute depth from a single RGB image. I used temporal smoothing for the videos in the main page.

**Comment by amirrezahesamian** [comment]
Yes, as you mentioned I visualized absolute 3D poses (preds_3d_kpt_mupots.mat). So in this case, somehow it needed to add an estimation error factor to the RootNet to fix absolute depth prediction results. Anyway thanks for the tips it was really helpful.

**Comment by amirrezahesamian** [comment]
Sorry that I am interrupting you again. I would like to ask about the temporal smoothing technique on 3D poses data that you mentioned, I guess is not used in your current code in these repositories. I would like to know is it possible to give me some tips about it.

**Comment by mks0601** [comment]
I used a median filter.

**Comment by amirrezahesamian** [comment]
@mks0601 appreciate that.

**Comment by SkyJoyTianle** [comment]
> Hello! I've worked on top @thimhh code, and managed to run on webcam with 2d visualization. Now I'm trying to visualize 3d results and deal with confidence score along each skeleton node.
> 
> Please, if you find better ways to code this or visualize 3d results or confidence score, It would help a lot!
> 
> Here is the full script:
> 
> ```
> from torchvision import transforms
> import argparse
> import numpy as np
> import cv2
> from config import cfg
> import torch
> from base import Tester
> import torch.backends.cudnn as cudnn
> from utils.vis import vis_keypoints
> from common.utils.vis import vis_3d_skeleton
> 
> def parse_args():
>     parser = argparse.ArgumentParser()
>     parser.add_argument('--gpu', type=str, dest='gpu_ids', default='0')
>     parser.add_argument('--test_epoch', type=str, dest='test_epoch', default=24)
>     args = parser.parse_args()
> 
>     # test gpus
>     if not args.gpu_ids:
>         assert 0, print("Please set proper gpu ids")
> 
>     assert args.test_epoch, 'Test epoch is required.'
> 
>     return args
> 
> 
> cam = cv2.VideoCapture(0)
> 
> dim = (256, 256)
> 
> args = parse_args()
> cfg.set_args(args.gpu_ids)
> cudnn.fastest = True
> cudnn.benchmark = True
> cudnn.deterministic = False
> cudnn.enabled = True
> 
> tester = Tester(args.test_epoch)
> tester._make_batch_generator()
> tester._make_model()
> 
> with torch.no_grad():
>     for camx in range(1, 100000):
> 
>         s, original_image = cam.read()
> 
>         original_image = cv2.resize(original_image, dim, interpolation=cv2.INTER_AREA)
>         image = np.asarray(original_image)
>         img_height, img_width, img_channels = image.shape
>         for i in range(img_channels):
>             image[:, :, i] = np.clip(image[:, :, i] * 1, 0, 255)
>         image = image[:, :, ::-1].copy()
>         image = image.astype(np.float32)
> 
>         data_transforms = transforms.Compose([
>             # transforms.RandomResizedCrop(256),
>             transforms.ToTensor(),
>             transforms.Normalize(mean=cfg.pixel_mean, std=cfg.pixel_std)
>         ])
> 
>         image_tensor = data_transforms(image)
> 
>         # Convert to 4-D from 3-D image
>         image_tensor = image_tensor.unsqueeze(0)
> 
>         coord_out = tester.model(image_tensor)
>         tensors = list(coord_out.data[0])
> 
>         vis_2d = True
>         # Working 2d visualization
>         if vis_2d:
>             keypoints = np.zeros((3, tester.joint_num))
>             keypoints[:2, :] = coord_out[0, :, :2].cpu().numpy().transpose(1, 0) / cfg.output_shape[0] * \
>                                cfg.input_shape[0]
>             keypoints[2, :] = 1
>             tmpimg = vis_keypoints(original_image, keypoints, tester.skeleton)
> 
>         # Not working 3d visualization
>         if not vis_2d:
>             keypoints = np.zeros((3, tester.joint_num))
>             keypoints[:2, :] = coord_out[0, :, :2].cpu().numpy().transpose(1, 0) / cfg.output_shape[0] * \
>                                cfg.input_shape[0]
>             keypoints[2, :] = 1
>             keypoints = keypoints.transpose()
> 
>             tmpimg = vis_3d_skeleton(original_image, keypoints, tester.skeleton)
> 
>         cv2.imshow("window", tmpimg)
>         cv2.waitKey(1)
> ```

how can I do it in multiperson, here is just for single person and the vis_3d part is wrong like this:
Traceback (most recent call last):
  File "G:/Japan/Seminar/implement/3DMPPE_POSENET_RELEASE-master/main/video.py", line 88, in <module>
    tmpimg = vis_3d_skeleton(original_image, keypoints, tester.skeleton)
  File ".\common\utils\vis.py", line 61, in vis_3d_skeleton
    ax.plot(x, z, -y, c=colors[l], linewidth=2)
  File "G:\Ana\envs\pytorch_gpu\lib\site-packages\mpl_toolkits\mplot3d\axes3d.py", line 1538, in plot
    zs = np.broadcast_to(zs, len(xs))
  File "<__array_function__ internals>", line 6, in broadcast_to
  File "C:\Users\tianl\AppData\Roaming\Python\Python36\site-packages\numpy\lib\stride_tricks.py", line 182, in broadcast_to
    return _broadcast_to(array, shape, subok=subok, readonly=True)
  File "C:\Users\tianl\AppData\Roaming\Python\Python36\site-packages\numpy\lib\stride_tricks.py", line 127, in _broadcast_to
    op_flags=['readonly'], itershape=shape, order='C')
ValueError: input operand has more dimensions than allowed by the axis remapping

Process finished with exit code 1

when I set vis_2d=False

**Comment by mks0601** [comment]
I think you can debug this by yourself. The error comes from vis_3d_skeleton function. I think you'd better check dimension of input argument of that function.

**Comment by SkyJoyTianle** [comment]
> I think you can debug this by yourself. The error comes from vis_3d_skeleton function. I think you'd better check dimension of input argument of that function.

Okay, thanks for reply, then how about multi version, for this is a single one

**Comment by AndiDemon** [comment]
> > Hello! I've worked on top @thimhh code, and managed to run on webcam with 2d visualization. Now I'm trying to visualize 3d results and deal with confidence score along each skeleton node.
> > Please, if you find better ways to code this or visualize 3d results or confidence score, It would help a lot!
> > Here is the full script:
> > ```
> > from torchvision import transforms
> > import argparse
> > import numpy as np
> > import cv2
> > from config import cfg
> > import torch
> > from base import Tester
> > import torch.backends.cudnn as cudnn
> > from utils.vis import vis_keypoints
> > from common.utils.vis import vis_3d_skeleton
> > 
> > def parse_args():
> >     parser = argparse.ArgumentParser()
> >     parser.add_argument('--gpu', type=str, dest='gpu_ids', default='0')
> >     parser.add_argument('--test_epoch', type=str, dest='test_epoch', default=24)
> >     args = parser.parse_args()
> > 
> >     # test gpus
> >     if not args.gpu_ids:
> >         assert 0, print("Please set proper gpu ids")
> > 
> >     assert args.test_epoch, 'Test epoch is required.'
> > 
> >     return args
> > 
> > 
> > cam = cv2.VideoCapture(0)
> > 
> > dim = (256, 256)
> > 
> > args = parse_args()
> > cfg.set_args(args.gpu_ids)
> > cudnn.fastest = True
> > cudnn.benchmark = True
> > cudnn.deterministic = False
> > cudnn.enabled = True
> > 
> > tester = Tester(args.test_epoch)
> > tester._make_batch_generator()
> > tester._make_model()
> > 
> > with torch.no_grad():
> >     for camx in range(1, 100000):
> > 
> >         s, original_image = cam.read()
> > 
> >         original_image = cv2.resize(original_image, dim, interpolation=cv2.INTER_AREA)
> >         image = np.asarray(original_image)
> >         img_height, img_width, img_channels = image.shape
> >         for i in range(img_channels):
> >             image[:, :, i] = np.clip(image[:, :, i] * 1, 0, 255)
> >         image = image[:, :, ::-1].copy()
> >         image = image.astype(np.float32)
> > 
> >         data_transforms = transforms.Compose([
> >             # transforms.RandomResizedCrop(256),
> >             transforms.ToTensor(),
> >             transforms.Normalize(mean=cfg.pixel_mean, std=cfg.pixel_std)
> >         ])
> > 
> >         image_tensor = data_transforms(image)
> > 
> >         # Convert to 4-D from 3-D image
> >         image_tensor = image_tensor.unsqueeze(0)
> > 
> >         coord_out = tester.model(image_tensor)
> >         tensors = list(coord_out.data[0])
> > 
> >         vis_2d = True
> >         # Working 2d visualization
> >         if vis_2d:
> >             keypoints = np.zeros((3, tester.joint_num))
> >             keypoints[:2, :] = coord_out[0, :, :2].cpu().numpy().transpose(1, 0) / cfg.output_shape[0] * \
> >                                cfg.input_shape[0]
> >             keypoints[2, :] = 1
> >             tmpimg = vis_keypoints(original_image, keypoints, tester.skeleton)
> > 
> >         # Not working 3d visualization
> >         if not vis_2d:
> >             keypoints = np.zeros((3, tester.joint_num))
> >             keypoints[:2, :] = coord_out[0, :, :2].cpu().numpy().transpose(1, 0) / cfg.output_shape[0] * \
> >                                cfg.input_shape[0]
> >             keypoints[2, :] = 1
> >             keypoints = keypoints.transpose()
> > 
> >             tmpimg = vis_3d_skeleton(original_image, keypoints, tester.skeleton)
> > 
> >         cv2.imshow("window", tmpimg)
> >         cv2.waitKey(1)
> > ```
> 
> how can I do it in multiperson, here is just for single person and the vis_3d part is wrong like this:
> Traceback (most recent call last):
> File "G:/Japan/Seminar/implement/3DMPPE_POSENET_RELEASE-master/main/video.py", line 88, in
> tmpimg = vis_3d_skeleton(original_image, keypoints, tester.skeleton)
> File ".\common\utils\vis.py", line 61, in vis_3d_skeleton
> ax.plot(x, z, -y, c=colors[l], linewidth=2)
> File "G:\Ana\envs\pytorch_gpu\lib\site-packages\mpl_toolkits\mplot3d\axes3d.py", line 1538, in plot
> zs = np.broadcast_to(zs, len(xs))
> File "<**array_function** internals>", line 6, in broadcast_to
> File "C:\Users\tianl\AppData\Roaming\Python\Python36\site-packages\numpy\lib\stride_tricks.py", line 182, in broadcast_to
> return _broadcast_to(array, shape, subok=subok, readonly=True)
> File "C:\Users\tianl\AppData\Roaming\Python\Python36\site-packages\numpy\lib\stride_tricks.py", line 127, in _broadcast_to
> op_flags=['readonly'], itershape=shape, order='C')
> ValueError: input operand has more dimensions than allowed by the axis remapping
> 
> Process finished with exit code 1
> 
> when I set vis_2d=False

I am following this code to visualize the pose.
I tried to understand the error message with missing 'k_value' for the forward function in model.py.
However, I could not get any clue what is this 'k_value' in any related files. 
Thanks
Traceback (most recent call last):
  File "poseWebcam.py", line 66, in <module>
    coord_out = tester.model(image_tensor)
  File "/home/andidemon/anaconda3/envs/3DPose/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/andidemon/anaconda3/envs/3DPose/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 153, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/andidemon/anaconda3/envs/3DPose/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
TypeError: forward() missing 1 required positional argument: 'k_value'

**Comment by DA-fromindia** [comment]
> Hello! I've worked on top @thimhh code, and managed to run on webcam with 2d visualization. Now I'm trying to visualize 3d results and deal with confidence score along each skeleton node.
> 
> Please, if you find better ways to code this or visualize 3d results or confidence score, It would help a lot!
> 
> Here is the full script:
> 
> ```
> from torchvision import transforms
> import argparse
> import numpy as np
> import cv2
> from config import cfg
> import torch
> from base import Tester
> import torch.backends.cudnn as cudnn
> from utils.vis import vis_keypoints
> from common.utils.vis import vis_3d_skeleton
> 
> def parse_args():
>     parser = argparse.ArgumentParser()
>     parser.add_argument('--gpu', type=str, dest='gpu_ids', default='0')
>     parser.add_argument('--test_epoch', type=str, dest='test_epoch', default=24)
>     args = parser.parse_args()
> 
>     # test gpus
>     if not args.gpu_ids:
>         assert 0, print("Please set proper gpu ids")
> 
>     assert args.test_epoch, 'Test epoch is required.'
> 
>     return args
> 
> 
> cam = cv2.VideoCapture(0)
> 
> dim = (256, 256)
> 
> args = parse_args()
> cfg.set_args(args.gpu_ids)
> cudnn.fastest = True
> cudnn.benchmark = True
> cudnn.deterministic = False
> cudnn.enabled = True
> 
> tester = Tester(args.test_epoch)
> tester._make_batch_generator()
> tester._make_model()
> 
> with torch.no_grad():
>     for camx in range(1, 100000):
> 
>         s, original_image = cam.read()
> 
>         original_image = cv2.resize(original_image, dim, interpolation=cv2.INTER_AREA)
>         image = np.asarray(original_image)
>         img_height, img_width, img_channels = image.shape
>         for i in range(img_channels):
>             image[:, :, i] = np.clip(image[:, :, i] * 1, 0, 255)
>         image = image[:, :, ::-1].copy()
>         image = image.astype(np.float32)
> 
>         data_transforms = transforms.Compose([
>             # transforms.RandomResizedCrop(256),
>             transforms.ToTensor(),
>             transforms.Normalize(mean=cfg.pixel_mean, std=cfg.pixel_std)
>         ])
> 
>         image_tensor = data_transforms(image)
> 
>         # Convert to 4-D from 3-D image
>         image_tensor = image_tensor.unsqueeze(0)
> 
>         coord_out = tester.model(image_tensor)
>         tensors = list(coord_out.data[0])
> 
>         vis_2d = True
>         # Working 2d visualization
>         if vis_2d:
>             keypoints = np.zeros((3, tester.joint_num))
>             keypoints[:2, :] = coord_out[0, :, :2].cpu().numpy().transpose(1, 0) / cfg.output_shape[0] * \
>                                cfg.input_shape[0]
>             keypoints[2, :] = 1
>             tmpimg = vis_keypoints(original_image, keypoints, tester.skeleton)
> 
>         # Not working 3d visualization
>         if not vis_2d:
>             keypoints = np.zeros((3, tester.joint_num))
>             keypoints[:2, :] = coord_out[0, :, :2].cpu().numpy().transpose(1, 0) / cfg.output_shape[0] * \
>                                cfg.input_shape[0]
>             keypoints[2, :] = 1
>             keypoints = keypoints.transpose()
> 
>             tmpimg = vis_3d_skeleton(original_image, keypoints, tester.skeleton)
> 
>         cv2.imshow("window", tmpimg)
>         cv2.waitKey(1)
> ```

Hi @lucas-amin 
I put "snapshot_24.pth.tar" in output/model_dump

it gives this error

	`Missing key(s) in state_dict: "module.root.deconv_layers.0.weight", "module.root.deconv_layers.1.weight", "module.root.deconv_layers.1.bias", "module.root.deconv_layers.1.running_mean", "module.root.deconv_layers.1.running_var", "module.root.deconv_layers.3.weight", "module.root.deconv_layers.4.weight", "module.root.deconv_layers.4.bias", "module.root.deconv_layers.4.running_mean", "module.root.deconv_layers.4.running_var", "module.root.deconv_layers.6.weight", "module.root.deconv_layers.7.weight", "module.root.deconv_layers.7.bias", "module.root.deconv_layers.7.running_mean", "module.root.deconv_layers.7.running_var", "module.root.xy_layer.weight", "module.root.xy_layer.bias", "module.root.depth_layer.weight", "module.root.depth_layer.bias". `


	`Unexpected key(s) in state_dict: "module.head.deconv_layers.0.weight", "module.head.deconv_layers.1.weight", "module.head.deconv_layers.1.bias", "module.head.deconv_layers.1.running_mean", "module.head.deconv_layers.1.running_var", "module.head.deconv_layers.1.num_batches_tracked", "module.head.deconv_layers.3.weight", "module.head.deconv_layers.4.weight", "module.head.deconv_layers.4.bias", "module.head.deconv_layers.4.running_mean", "module.head.deconv_layers.4.running_var", "module.head.deconv_layers.4.num_batches_tracked", "module.head.deconv_layers.6.weight", "module.head.deconv_layers.7.weight", "module.head.deconv_layers.7.bias", "module.head.deconv_layers.7.running_mean", "module.head.deconv_layers.7.running_var", "module.head.deconv_layers.7.num_batches_tracked", "module.head.final_layer.weight", "module.head.final_layer.bias". `

probably i had a wrong model!, can you suggest a link?? @mks0601

**Comment by zhangy76** [comment]
Thanks for the discussion.

**Comment by mks0601** [comment]
Hi guys, I made a demo code. Please check out https://github.com/mks0601/3DMPPE_POSENET_RELEASE/blob/master/demo/demo.py

**Comment by vra** [comment]
Hi @mks0601 ,
I use `demo.py` and change `input.jpg` to image below, the results were somewhat weird. I tried original `input.jpg`, the results were fine.  I also tried some images with different ratio of height and width, no good results. Could you please have a look at this issue? Thanks

## output_mesh_lixel.jpg of my image:
![image](https://user-images.githubusercontent.com/5562395/95583150-4e397200-0a6e-11eb-9021-ff1f4b0effef.png)
## output_mesh_param.jpg of my image:
![image](https://user-images.githubusercontent.com/5562395/95583168-52fe2600-0a6e-11eb-827e-f2df2857c8f3.png)


## output_mesh_lixel.jpg of original input.jpg:
![image](https://user-images.githubusercontent.com/5562395/95583574-ec2d3c80-0a6e-11eb-8d2e-b9f4f57adce0.png)
## output_mesh_param.jpg of original input.jpg:
![image](https://user-images.githubusercontent.com/5562395/95583635-036c2a00-0a6f-11eb-85b4-abb44e586166.png)

**Comment by mks0601** [comment]
Did you set proper bounding box coordinates and human root joint depth?

**Comment by vra** [comment]
> Did you set proper bounding box coordinates and human root joint depth?

No, I didn't change these variables.  I will try again, Thanks.

**Comment by vra** [comment]
Hi @mks0601 ,
I change the bbox and root joint depth to right variable, the results become reasonable. Thanks for your help

**Comment by mks0601** [comment]
Good for you!
