### ISSUE TITLE
How to get MultiPerson data?

### ISSUE THREAD

**Issue by thimhh** [mks0601/3DMPPE_POSENET_RELEASE#37]
Hi,
I just try to learn about AI and I really like this implementation because with it I can explain the power of AI better to other people. But I have just a very simple notebook and an Nvidia Jetson Nano for my experiments. I was able to build a modified script derived from test.py to read single images without dataset creation and I can attach a webcam to have a continous live feed which I can visualize live locally and even remote on the notebook (ok, since it's a Jetson Nano there is of course some lag and just a very low fps...). So since I can't do any training with this hardware I use your provided models to infere. But I have always only  one person detected. Can you give me some advice how to get there? Will this only work with a MuPots trained model? I have tried all three provided samples. If you're interested in my examples just let me know, but they're really quick and dirty...

**Comment by mks0601** [comment]
The input of this paper is cropped single person image. I did the human detection using Detectron2 (https://github.com/facebookresearch/detectron2)

**Comment by thimhh** [comment]
Ok, I thought already something like that but had not time to dive deeper into it... Thanks
