### ISSUE TITLE
Where do I get the file "bbox_root_human36m_output.json"?

### ISSUE THREAD

**Issue by NaveenSehgal** [mks0601/3DMPPE_POSENET_RELEASE#4]
I'm trying to run the test code with the model pre-trained on H36M Protocol 1. The download links in the "Results" section of the README are different than the one `bbox_root_human36m_output.json` required by the code. 

The files linked in the README is `bbox_human36m_output.json`. I tried re-naming it to `bbox_root_human36m_output.json` to see if it was just a naming error, however I get the following errors then: 

```
  File "test.py", line 41, in main
    tester._make_batch_generator()
  File "/home/sehgal.n/3DMPPE_POSENET_RELEASE/main/../common/base.py", line 136, in _make_batch_generator
    testset = eval(cfg.testset)("test")
  File "/home/sehgal.n/3DMPPE_POSENET_RELEASE/main/../data/Human36M/Human36M.py", line 31, in __init__
    self.data = self.load_data()
  File "/home/sehgal.n/3DMPPE_POSENET_RELEASE/main/../data/Human36M/Human36M.py", line 86, in load_data
    bbox_root_result[str(annot[i]['image_id'])] = {'bbox': np.array(annot[i]['bbox']), 'root': np.array(annot[i]['root_cam'])}
```

Thanks!

**Comment by mks0601** [comment]
Hi, I should have been more clear. You need to run RootNet(https://github.com/mks0601/3DMPPE_ROOTNET_RELEASE) to get `bbox_root_human36m_output.json`. I'll run RootNet and upload the `bbox_root` file for all dataset soon.

**Comment by mks0601** [comment]
Hi, I uploaded it. You can download in README.

**Comment by NaveenSehgal** [comment]
Ah ok, thanks, so running PoseNet requires having the output of RootNet then? I was hoping to train and test PoseNet on a custom 3D single person pose dataset (similar to H36M), could I do that with just PoseNet?

**Comment by mks0601** [comment]
I think it will be very clarified if you read my paper. The PoseNet can only obtain root-relative 3D pose like all of the previous 3D human pose estimation papers. If you want to get absolute 3D pose, you need to use output of the RootNet.

**Comment by UmarSpa** [comment]
Can't find the link to download bbox_root (I am especially interested in bbox_root_human36m_output.json). Can you please point me where you uploaded it ? Thanks
