### ISSUE TITLE
Unexpected Keys in state_dict when running on CPU

### ISSUE THREAD

**Issue by usamahjundia** [mks0601/3DMPPE_POSENET_RELEASE#41]
i wrote a custom code which IMO is more or less the same with the original code to load the weights in the model and return the model with loaded weight, like so:
```py
def modelLoader(modelpath,resnet_type,joint_num,gpu):
    model = get_pose_net(resnet_type,False,joint_num)
    ckpt = torch.load(modelpath)
    model.load_state_dict(ckpt['network'])
    model.eval()
    if gpu != "-1":
        device = torch.device(f"cuda:{gpu}")
        model.cuda(device=device)
    return model
```

I downloaded the pretrained models and tried loading the Human3.6M one in the Protocol1 folder, and met this error caused by basically every layer names having "module." preprended to them. For example, the loader expected "head.deconv_layers.7.running_var" but in the provided pretrained weight, i got "module.head.deconv_layers.7.running_var"

Is this intended?

For a quick hack, i basically just loop over the dict and remove the prepended module, but i just want to know if this is intended and i somehow misused something somewhere

Edit : This.. is basically what happens when you use pytorch on multi GPU settings. I have no idea the exact detail as i am not familiar with pytorch, but the module. prefix is caused by that.

This is an example script so you can easily filter remove the prefix, so you can easily load.

```
def convert(source,dest):
    statedict = torch.load(source)
    networkdict = statedict['network']
    res = []
    for k, v in tqdm(networkdict.items()):
        if k.split(".")[0] == 'module':
            k = k[7:]
        res.append((k,v))
    resdict = OrderedDict(res)

    torch.save(resdict,dest)
```

**Comment by usamahjundia** [comment]
For a quick hack, i basically just loop over the dict and remove the prepended module, but i just want to know if this is intended and i somehow misused something somewhere

**Comment by mks0601** [comment]
The 'module' thing is because my model is wrapped by nn.DataParallel module in pytorch.

**Comment by usamahjundia** [comment]
Thank you for the addition. I have actually solved this problem, along with some other problems when running on CPU. For those running on CPU encountering error during feedforward, just replace the broadcasted arange with simple torch.arange and it solves the problem
