### ISSUE TITLE
About Human3.6 dataset

### ISSUE THREAD

**Issue by Sadegh28** [mks0601/3DMPPE_POSENET_RELEASE#42]

**Comment by Sadegh28** [comment]
Hello and thanks for your great work. I'm trying to understand your network. Which version of the Human3.6 dataset have you used? As I know, this dataset contains images, each with a single person, so how did you trained your network to work on multi-person cases?

**Comment by mks0601** [comment]
The human detector detects all humans in the input image and my PoseNet takes a cropped human image.
Please check out my paper.

**Comment by Sadegh28** [comment]
Thanks for your answer. I found two version of the human3.6 dataset in the imar website. The first one contains a complete dataset and the other one which has smaller size and  designed for ECCV dataset. Which version have you used?

**Comment by mks0601** [comment]
You can download preprocessed h36m data in README.

**Comment by mks0601** [comment]
https://github.com/mks0601/3DMPPE_POSENET_RELEASE/blob/master/README.md
