### ISSUE TITLE
checkpoint size doesn't match with model.

### ISSUE THREAD

**Issue by khg2478** [mks0601/3DMPPE_POSENET_RELEASE#43]
Hi.

I want to test your model but it seems that there is difference between trained model and a model. Below is the error message I got. Could you tell me how I can fix this?

Thanks.

size mismatch for module.head.final_layer.weight: copying a param with shape torch.Size([1152, 256, 1, 1]) from checkpoint, the shape in current model is torch.Size([1088, 256, 1, 1]).
	size mismatch for module.head.final_layer.bias: copying a param with shape torch.Size([1152]) from checkpoint, the shape in current model is torch.Size([1088]).

**Comment by mks0601** [comment]
Hi, please make sure the mode you are trying to load is from testset of config.py

**Comment by SangbumChoi** [comment]
I'm working with fixing this problem because implementing with different baseline.

I think this problem was originated from joint_number I guess, I will comment it when I fix this problem

**Comment by SangbumChoi** [comment]
This problem was about the default datasets. Different datasets have different number of joint number. As you train with only Human3.6M for 3d dataset then I think you should rearrange the joint number. I think the author of this code trained on MuCo and also Human3.6M
