### ISSUE TITLE
Training difference between PoseNet and Integral-Human-Pose

### ISSUE THREAD

**Issue by wanghonghui1998** [mks0601/3DMPPE_POSENET_RELEASE#44]
Hello! Thanks for your great work!
I use the bbox and root information you provided to test a model trained on Integral-Human-Pose project(https://github.com/JimmySuen/integral-human-pose), but I got pool performance(MPJPE 130mm using Protocol2).
If I change the bbox to gt bbox and use the root information you provided, I got 54mm.
I thought the reason would be the difference of bbox of Human3.6M during training, so I process the bbox as you did and train the model. But I still got pool performance(MPJPE 123mm using Protocol2).
Can you help me find out the reason why bbox influence so much?  Can you explain the main difference between your PoseNet and the Integral-Human-Pose project?

**Comment by mks0601** [comment]
If you got 54mm MPJPE when using GT bbox, then I think there would be marginal difference on bbox processing part between mine and theirs.
Have you checked cropped human images when using my bbox on their code?

**Comment by wanghonghui1998** [comment]
Hi, thanks for your quick reply! 
I have checked the cropped human images. The first one is GT bbox after preprocessing, the second is  your bbox. Compared to GT bbox, the center point of the second one shifts a little and the size is smaller. 
<img width="978" alt="截屏2020-03-25下午6 21 57" src="https://user-images.githubusercontent.com/48725183/77534815-4ea85c00-6ed4-11ea-8ddb-e911d5e5c8bc.png">
<img width="978" alt="截屏2020-03-25下午6 21 46" src="https://user-images.githubusercontent.com/48725183/77534816-4ea85c00-6ed4-11ea-9b76-4782318a84cd.png">

**Comment by wanghonghui1998** [comment]
I did some experiments. Using the center point of your bbox and the size of GT bbox, I got 80mm. Using the size of your bbox and the center point of GT bbox, I got 124mm. I think the original project of integral-human-pose may overfit to the size and location of bbox, how do you fix it?

**Comment by mks0601** [comment]
Ah now I can remember. I read their code about one year ago (first of the last year). As I remember, they obtain bounding box by 
1) construct 3D bounding box around the groundtruth 3D pelvis position.
2) project the 3D bbox to the 2D space and use that.

I also found that training a model by calculating bbox following them results in poor generalization on various bboxes.

**Comment by mks0601** [comment]
Have you changed bbox calculation code to mine and trained another model?
