### ISSUE TITLE
Problem with the loss

### ISSUE THREAD

**Issue by marcvoegele-fhnw** [mks0601/3DMPPE_POSENET_RELEASE#45]
As I see the coord in ResPoseNet (model.py) is something like this:
[['Head_Top-pred-Coord_X-sum over all people', ....],['Head_Top-pred-Coord_Y-sum over all people', ....],['Head_Top-pred-Coord_Z-sum over all people', ....]]

and target_coord is something like this:
[['Head_Top-real-Coord_X-sum over all people', ....],['Head_Top-real-Coord_Y-sum over all people', ....],['Head_Top-real-Coord_Z-sum over all people', ....]]

But if I'm correct you can't do:
coord-target_coord

This example shows the problem:
Person_1:
Head_Top-pred-Coord_X = 0.6
Head_Top-real-Coord_X = 0.5

Person_2:
Head_Top-pred-Coord_X = 0.5
Head_Top-real-Coord_X = 0.6

Sum-Head_Top-pred-CoordX = 1.1
Sum-Head_Top-real-CoordX = 1.1

Sum-Sum = 0
But MPJPE should be 0.1.

Do you understand what I mean?
PS: Sorry for my bad english.

**Comment by mks0601** [comment]
Sorry I cannot understand. What is 'sum over all people'? I do not sum something for all people.
