### ISSUE TITLE
Transformation of 3D pose

### ISSUE THREAD

**Issue by zhangyahu1** [mks0601/3DMPPE_POSENET_RELEASE#46]
Hi, thanks for sharing your great work!

I notice that the xR and yR of the output from PoseNet are in coordiante while ZR is in camera coordiante. Could you please give me some hints about how to transfrom (xR, yR, ZR) to the 3D pose in camera coordiante to achieve the evaluation? Are the intrinsic camera parameters required? Thanks!

**Comment by mks0601** [comment]
For the quantitative evaluation, I use camera the given intrinsic parameters like [here](https://github.com/mks0601/3DMPPE_POSENET_RELEASE/blob/7df62e283ddc13303f0c4cf3fbd318dd5466eea6/data/Human36M/Human36M.py#L188).
However, there can be cases where the intrinsic parameters are unknown, for example images in MSCOCO dataset. For those cases, I use normalized intrinsic parameters and just show qualitative results like [here](https://github.com/mks0601/3DMPPE_POSENET_RELEASE/blob/7df62e283ddc13303f0c4cf3fbd318dd5466eea6/data/MSCOCO/MSCOCO.py#L100)

**Comment by zhangyahu1** [comment]
Thanks for your quick reply!

I find several recent work employ the architecture of Sun for 3D pose estiamtion. For evaluation on Human 3.6M dataset, they also use  intrinsic parameters to achieve back-projection process. Do you think it is unfair to compare with other existing methods without using ground truth information (i.e.,  intrinsic parameters) on Human3.6M dataset?

**Comment by mks0601** [comment]
You are right. There are some GT information involved during the test stage including camera depth, bbox, and camera intrinsic parameters.

Compared with them, ours only use intrinsic parametets, and actually, normalized one can be used like https://arxiv.org/abs/1809.04987 and https://arxiv.org/abs/1809.06079

**Comment by zhangyahu1** [comment]
Thanks!
