### ISSUE TITLE
about the dataset Human3.6m

### ISSUE THREAD

**Issue by SkyJoyTianle** [mks0601/3DMPPE_POSENET_RELEASE#48]
I can't download the images.tar.gzaa, can you help me

**Comment by mks0601** [comment]
Sorry for late reply. Could you provide me the error message? I can download it now.

**Comment by SkyJoyTianle** [comment]
> Sorry for late reply. Could you provide me the error message? I can download it now.

Thanks for reply, the error is it is failed to download from the google drive because of the network, but I can download other zip files

**Comment by mks0601** [comment]
Could you read the News section of the README and try that? I provided some tricks to download files from google drive.

**Comment by SkyJoyTianle** [comment]
Okay, thanks
