### ISSUE TITLE
about the vis matlab code

### ISSUE THREAD

**Issue by SkyJoyTianle** [mks0601/3DMPPE_POSENET_RELEASE#50]
could you told me how to run the matlab code:
this one is wrong: preds_2d_kpt = load('preds_2d_kpt_mupots.mat'); 
and 'MultiPersonTestSet\TS17_img_000000' is invalid

**Comment by mks0601** [comment]
What do you mean by 'wrong'? Did you prepare proper files at proper directories?

**Comment by SkyJoyTianle** [comment]
> What do you mean by 'wrong'? Did you prepare proper files at proper directories?

Thanks for reply, I put the two mat files in here: G:\Japan\Seminar\implement\3DMPPE_POSENET_RELEASE-master\vis\multi, 

and I also changed the root and save path like:

root_path = 'G:\Japan\Seminar\implement\3DMPPE_POSENET_RELEASEmaster\data\MuPoTS\data\MultiPersonTestSet\';
save_path = 'G:\Japan\Seminar\implement\3DMPPE_POSENET_RELEASE-master\vis\';

but the error is 

Error using load
Invalid field name: 'MultiPersonTestSet\TS17\img_000000'.

Error in draw_3Dpose_mupots (line 53)
    preds_2d_kpt = load('preds_2d_kpt_mupots.mat');

**Comment by mks0601** [comment]
Could you check whether you are saving the mat file which has key as MultiPersonTestSet\TS17\img_000000? As you can see at this [line](https://github.com/mks0601/3DMPPE_POSENET_RELEASE/blob/7df62e283ddc13303f0c4cf3fbd318dd5466eea6/data/MuPoTS/MuPoTS.py#L124), there is no MultiPersonTestSet\ at the key.

**Comment by SkyJoyTianle** [comment]
Okay, I will try it, thanks

**Comment by SkyJoyTianle** [comment]
> Could you check whether you are saving the mat file which has key as MultiPersonTestSet\TS17\img_000000? As you can see at this [line](https://github.com/mks0601/3DMPPE_POSENET_RELEASE/blob/7df62e283ddc13303f0c4cf3fbd318dd5466eea6/data/MuPoTS/MuPoTS.py#L124), there is no MultiPersonTestSet\ at the key.

Sorry, I still don't know how to do it, because in the .py file which produce the mat file is that name, the MultiPersonTestSet\ is produced by itself in the .py file and I didn't change it

Could you help me

**Comment by mks0601** [comment]
You may change the dataset directory? Anyway, you can just edit that line to not include MultiPersonTestSet\.

**Comment by SkyJoyTianle** [comment]
> You may change the dataset directory? Anyway, you can just edit that line to not include MultiPersonTestSet.

Okay, I have changed the link in the .py file, it's my fault, thanks~
