### ISSUE TITLE
Question about Bounding Boxes

### ISSUE THREAD

**Issue by marcvoegele-fhnw** [mks0601/3DMPPE_POSENET_RELEASE#51]
Why are all your bounding-boxes a square. Did you calculate anithing after bbox-extraction?

**Comment by mks0601** [comment]
Yes. Please refer to this [line](https://github.com/mks0601/3DMPPE_POSENET_RELEASE/blob/7df62e283ddc13303f0c4cf3fbd318dd5466eea6/data/Human36M/Human36M.py#L133). I use `process_bbox` function for all datasets.
