### ISSUE TITLE
Corrupted Pretrained Models

### ISSUE THREAD

**Issue by choward232** [mks0601/3DMPPE_POSENET_RELEASE#54]
I've been interested in testing out this model architecture, but it appears the pre-trained model files are corrupted and unable to be extracted. I've tried a number of different workarounds to no avail -- if you could reupload a non-corrupted version of the pretrained models, that would be great! Thanks

**Comment by mks0601** [comment]
Hi, maybe you are trying to extract something from downloaded, but please do not. It is not a compressed file. Just use the downloaded one for the testing.

**Comment by choward232** [comment]
Okay great, thanks for the clarification and the quick response! I'll give it a try
