### ISSUE TITLE
Could you provide the code to obatin parsed Human3.6m?

### ISSUE THREAD

**Issue by krumo** [mks0601/3DMPPE_POSENET_RELEASE#55]
Nice job! I wonder how do you generate the sampled frames and coco style annotation files from the original Human3.6m dataset. Would you mind sharing the code to process this dataset?

**Comment by mks0601** [comment]
Sure. I pushed the codes at `tool/Human36M` folder. You should run the matlab code first, and then the python code will wrap the output of the matlab code to json file.

**Comment by mks0601** [comment]
Note that you should define your path. I left some comments in the codes.

**Comment by krumo** [comment]
Thanks a lot! It is very helpful.

**Comment by shyanguan** [comment]
Hi @mks0601 , can you share scripts to process other datasets if it's convenient?

**Comment by mks0601** [comment]
Which datasets?
