### ISSUE TITLE
PoseNet modify

### ISSUE THREAD

**Issue by www516717402** [mks0601/3DMPPE_POSENET_RELEASE#56]
Thank your for great project. I have some question for help.
1. About PoseNet , your paper cite **Integral human pose regression**. What has been modify in this base?
2. In paper _As the results in the table are based on the same PoseNet, we can conclude that AUCrel, which is an evaluation of the root-relative 3D human pose estimation highly depends on the accuracy of the PoseNe_ from **8.3 Ablation study--Effect of the PoseNet**. However, Why this paper didn't focus on  PoseNet.

**Comment by mks0601** [comment]
Hi, 

1. Nothing special is changed from Integral.
2. As you can read from the introduction section, the main focus is not root-relative 3d human pose estimation, but absolute 3d multi-person pose estimation. The main technical novelty and contribution is RootNet.

**Comment by www516717402** [comment]
Thank you for reply. I apply this PoseNet in handpose, get a terrible result.

**Comment by mks0601** [comment]
I also applied PoseNet on hand pose dataset, and got good results. I think there must be some bugs in your code?

**Comment by www516717402** [comment]
Glad you have also tested on the gesture data set. PoseNet trained in FreidHand dataset, about 300epochs precise lower with hrnet 20epochs.
On which data set did you train?

**Comment by mks0601** [comment]
I tested my model on various datasets such as STB, RHD, FreiHand, and my own dataset submitted to ECCV 2020. I haven't compare mine with HRNet. By the way, HRNet is for 2D pose estimation, not 3D?

**Comment by www516717402** [comment]
Yes, HRNet is for 2D pose estimate. extract 2D points in PoseNet with HRNet 2D keypoints to compare. I will check my code carefully.Thank you.
Looking forward to your new paper.

**Comment by mks0601** [comment]
Perfect. Feel free to ask question here if you have any problem.

**Comment by www516717402** [comment]
ok, thanks.
