### ISSUE TITLE
About mesh(SMPL) lables

### ISSUE THREAD

**Issue by www516717402** [mks0601/3DMPPE_POSENET_RELEASE#57]
Hello, This problem is not related to this project.But I still hope your answer.
I already finish trained in hand dataset by PoseNet from your advise. Recently, I want add a branch by SMPL model to improve 3D PCK precise. 
There is no mosh(SMPL theta and beta) in STB、RHD、FreiHand dataset etc. How to translate 3D keypoints to mesh(SMPL theta beta)?

**Comment by mks0601** [comment]
https://github.com/vchoutas/smplify-x

**Comment by www516717402** [comment]
Thank your for help. I need to ask you another question.
Recently, I already transform FreiHand to mesh by [manopth](https://github.com/hassony2/manopth) . However, get 21 keypoints by manopth inequal from read training_xyz.json files directly. How you meet this question?
Sorry to bother you.
