### ISSUE TITLE
Wrong camera translation params  of human36m

### ISSUE THREAD

**Issue by KaifuZ** [mks0601/3DMPPE_POSENET_RELEASE#58]
The camera translation in all Human36M_subject_camera.json seem to be wrong.
for example: in Human36M_subject1_camera.json, 't' of '1' is [-346.05078140028075, 546.9807793144001, 5474.481087434061], but in matlab_meta.txt of s_01_act_02_subact_01_ca_01, the translation is 1841.107028 4955.284623 1563.445396.

**Comment by mks0601** [comment]
Maybe the original matlab_meta.txt file has t = -RT.
I modified t of json file to follow [new world2cam function ](https://github.com/mks0601/3DMPPE_POSENET_RELEASE/blob/374737a219cdd240163617973c983cca7d06cfe2/common/utils/pose_utils.py#L20).

**Comment by KaifuZ** [comment]
thx!
