### ISSUE TITLE
Why do you crop the closest person to the camera?

### ISSUE THREAD

**Issue by lhyfst** [mks0601/3DMPPE_POSENET_RELEASE#59]
https://github.com/mks0601/3DMPPE_POSENET_RELEASE/blob/15446c408f664702b348eb5a7f75250b28d14ed6/data/MuCo/MuCo.py#L40-L60

Does this data preprocess method follow other previous works?

**Comment by mks0601** [comment]
Yes I follwed http://gvv.mpi-inf.mpg.de/projects/SingleShotMultiPerson/

**Comment by lhyfst** [comment]
I see. Thanks~
