### ISSUE TITLE
There are no 'preds_2d_kpt_$DB_NAME.mat' and 'preds_3d_kpt_$DB_NAME.mat' files after testing

### ISSUE THREAD

**Issue by Eooming** [mks0601/3DMPPE_POSENET_RELEASE#60]
In the '3D visualization' part, you said 'Place your test result files (preds_2d_kpt_$DB_NAME.mat, preds_3d_kpt_$DB_NAME.mat) in single or multi folder.' But I cannot find any of them after testing. There are only a 'bbox_root_pose_output.json' file. Could you tell me where the problem might be? Thx a lot.

**Comment by mks0601** [comment]
You can get the files when you run test.
This [line](https://github.com/mks0601/3DMPPE_POSENET_RELEASE/blob/15446c408f664702b348eb5a7f75250b28d14ed6/data/MSCOCO/MSCOCO.py#L176) output the mat file.
