### ISSUE TITLE
output_pose_3d is wrong when running demo.py

### ISSUE THREAD

**Issue by Eooming** [mks0601/3DMPPE_POSENET_RELEASE#62]
Hi, there.
Firstly, thank you for your contribution. But there are some problem when I run demo.py
I fill the 'root_depth' result generated from ROOTNET into demo.py of POSENET. The result of 2d pose is correct, but 3d pose is strength.
Could you give me some advice to solve this.

regreds.
Feng

ps: it's a pity that the picture of 3d pose cannot be upload correctly

**Comment by mks0601** [comment]
I can't get what you mean by weird 3d pose. If you are talking about the viewpoint, you can drag and drop the window to rotate the 3d pose like below.
![스크린샷 2020-08-06 오후 4 26 36](https://user-images.githubusercontent.com/13601723/89503647-ca5ed180-d801-11ea-9030-a2e73b1c9f2f.png)
![스크린샷 2020-08-06 오후 4 26 44](https://user-images.githubusercontent.com/13601723/89503653-cd59c200-d801-11ea-9e90-4a2db53165e1.png)
![스크린샷 2020-08-06 오후 4 26 51](https://user-images.githubusercontent.com/13601723/89503654-cdf25880-d801-11ea-9f9a-a40954106f59.png)
![스크린샷 2020-08-06 오후 4 26 56](https://user-images.githubusercontent.com/13601723/89503657-ce8aef00-d801-11ea-84ca-6572eeabc3c1.png)

**Comment by Eooming** [comment]
Thanks a lot. The answer is what I want.
By the way, I wonder if there is any way to show multiple subject in a system by using demo.py, since the demo.py shows the 3d pose of only one subject.

Regards.

**Comment by mks0601** [comment]
I guess you can easily hack the demo code and extend it to the multiple subject case?

**Comment by mks0601** [comment]
You can show all 3d poses of subjects like [this]( https://github.com/mks0601/3DMPPE_POSENET_RELEASE/blob/50ff63291a6599e7c5fe210b55da6b0daea4d230/demo/demo.py#L123).
The 3d poses of all subjects should be (x,y,z camera-centered), not [(x,y pixel, z root-relative depth)](https://github.com/mks0601/3DMPPE_POSENET_RELEASE/blob/50ff63291a6599e7c5fe210b55da6b0daea4d230/demo/demo.py#L101)

**Comment by Eooming** [comment]
Thank you for your suggestion.
Have a nice day~
