### ISSUE TITLE
 a question about the inputs of mode in demo

### ISSUE THREAD

**Issue by elk-april** [mks0601/3DMPPE_POSENET_RELEASE#63]
your idea is so nice.
But when i run the demo.py, I noticed that the output of 'generate_patch_image' is np.float32,and then feed it into 
'transform = transforms.Compose([transforms.ToTensor(), transforms.Normalize(mean=cfg.pixel_mean, std=cfg.pixel_std)])'
the output just likes below:
![image](https://user-images.githubusercontent.com/22853879/89747382-2b7ff100-daf1-11ea-8696-0c8bd47b1a35.png)

And i find the train dataset also like this, that means the inputs of model is not between 0 and 1 at all.In fact, the augmented img is 0-255 and then totensor, normalize(mean=(0.485, 0.456, 0.406,std=0.229, 0.224, 0.225)). 

wish for your responds.
repect.

**Comment by mks0601** [comment]
Hi, that was my mistake at the early of this project :( I found this mistake after getting accept at ICCV, so I just stick to the current version. I found that there is marginal performance difference when I normalize the input in [0,1] and train/test again.

**Comment by elk-april** [comment]
Thanks for your respond..
But I met a bug.No matter which normalization (0-1 or follow yours )I choose, the outputs of model( trained by myself, about 5 epochs) are all same, just like bellow:
![image](https://user-images.githubusercontent.com/22853879/89762664-73b80700-db23-11ea-9b03-bce27b3ca15b.png)
Have you met this bug? Or could you tell me anything reasons for this bug?

**Comment by mks0601** [comment]
I haven't met this bug, but some folks said updating torchvision helped.
Could you test demo with provided the snapshot?

**Comment by elk-april** [comment]
I tried to change torchvision =0.3.0 to =0.4.2，but the bug still exists,
the demo you provided can work, So I think there is something bug in my train code,such as my custom dataset ....

**Comment by mks0601** [comment]
Yeah I think you'd better check your custom dataset code

**Comment by elk-april** [comment]
Thanks,I found the bug... 
Since I fogot to align the gt-keypoints and pred-keypoints, that means my pred-keypoints is between 0- 63, but gt-keypoints is between 0 - 255......
