### ISSUE TITLE
a question about mem_info() function

### ISSUE THREAD

**Issue by cheolsoonLee** [mks0601/3DMPPE_POSENET_RELEASE#64]
Hello, I'm really thankful for your contribution.

But, i have a question  while trying to run the code

In your code, mem_info() function is used. 
but there are not anything imported to use the function.

So, i couldn't run the code
 
what do i need to import to use mem_info() function?

Could you give me some advice to solve this.

Thank you.

**Comment by mks0601** [comment]
Sorry that function does nothing, but if you entered correct gpu ids, the mem_info would not be called. How did you run my code?

**Comment by cheolsoonLee** [comment]
I ran your code exactly as it was uploaded.

If so, 
In your code's  -> parser.add_argument('--gpu', type=str, dest=**'gpu_ids'**)

Is it correct to enter the gpu ID there?

Could you give me some advice to solve this.

Thanks for answering my question.

**Comment by mks0601** [comment]
Please read the instructions in README.
`python train.py --gpu 0-1`
