### ISSUE TITLE
Is there Multi-Person Demo?

### ISSUE THREAD

**Issue by YangJae96** [mks0601/3DMPPE_POSENET_RELEASE#65]
Hello. I have ran the demo code and I figured out it only detects one person's pose in the image.
Is there a way to show the result that detects multi-person and visualize all the poses?
or am I missing something from demo code??

Thank you very much in advance!
JWY

**Comment by mks0601** [comment]
Hi, I updated the demo. Now, it can handle multiple persons.

**Comment by YangJae96** [comment]
Thank you so Much!!!
