### ISSUE TITLE
MSCOCO keypoints with pre-trained model

### ISSUE THREAD

**Issue by d-cota** [mks0601/3DMPPE_POSENET_RELEASE#68]
Hi, I'm trying to obtain the eyes key points from PoseNet and I've seen that there are annotations for that in the MSCOCO dataset. I've also noticed that the pretrained model has been trained using MuCo + MSCOCO so I'm trying to figure it out if I can obtain from this model the eyes coordinates. In the demo script appear only the MuCo joint set, there is away to obtain the MSCOCO body points or I need to re-train the net? Thanks you

**Comment by mks0601** [comment]
Hi,

Unfortunately, MSCOCO is 2D pose dataset, so PoseNet cannot be trained on eye joint for the 3D pose estimation. Instead, you can check my new repo (https://github.com/mks0601/I2L-MeshNet_RELEASE). It predicts 3D human pose and mesh, and 3D eye coordinate can be obtained.

**Comment by d-cota** [comment]
Thanks you. But if I don't need the 3D estimation of the joints can I train the net only on the 2D dataset?

**Comment by mks0601** [comment]
For the 2D estimation, yes you can but you should change code a little bit. I think [hrnet](https://github.com/leoxiaobin/deep-high-resolution-net.pytorch) would be better for you if you are interested in only 2D estimation.

**Comment by d-cota** [comment]
Thanks you, appreciate so much your work!
