### ISSUE TITLE
The image is not divided by 255

### ISSUE THREAD

**Issue by simsim314** [mks0601/3DMPPE_POSENET_RELEASE#69]
I've printed the input mage in the demo file (which I run on CPU), from here:
https://github.com/mks0601/3DMPPE_POSENET_RELEASE/blob/master/demo/demo.py#L90

And the numbers of the input are not normally distributed, actually the original image is still in pixels. 

Here is an example from the print:
1095.9734, 1087.0845, 1095.9734,  ...,  189.3067,  375.9734 

What is funny that it's all still working pretty well. When I add 
img /= 255
The results seems to be the same.

**Comment by mks0601** [comment]
Yes I know this issue and this was my mistake when I implemented this project. However, this kind of normalization is not necessary because the learnable weights can be adjusted to perform 3D human pose estimation from 0~255 pixel values. Where did you do img /= 255?

**Comment by simsim314** [comment]
Here:
https://github.com/mks0601/3DMPPE_POSENET_RELEASE/blob/cac0b5b910a1267cf1f7bc17a435602c2d6daf44/demo/demo.py#L90

 img = transform(img/255).cuda()[None,:,:,:]

**Comment by mks0601** [comment]
Hmm.. Anyway, not dividing 255 is not a wrong implementation, and was my mistake. Current released pre-trained models will work well on current code.
