### ISSUE TITLE
PCKabs for MuPoTS

### ISSUE THREAD

**Issue by GUO-W** [mks0601/3DMPPE_POSENET_RELEASE#70]
Hi, I would like to ask how you calculate the PCKabs reported in your supplemental material please? Do you use mpii_mupots_multiperson_eval(0,0) and (1,0) directly for the PCKh@150mm abs? 

Because I tried with the testing result on MuPoTS, mpii_mupots_multiperson_eval(0,1) and (1,1) gives the same relative results with your reported ones, but the mpii_mupots_multiperson_eval(0,0)  gets 80.2 as result (which is not reasonable).

Thank you very much for your help!

**Comment by mks0601** [comment]
I think your output 3D pose has the same root location with that of GT 3D pose?

**Comment by GUO-W** [comment]
Oh yes, I was using the ground truth root but not the detected ones. My bad. Sorry for disturbing with the stupid question ;)  Thanks a lot!
