### ISSUE TITLE
About MuPoTS-3D evaluation

### ISSUE THREAD

**Issue by seonghyunkim1212** [mks0601/3DMPPE_POSENET_RELEASE#75]
Hi, first of all, thank you for your great work.

I have a question about evaluating the mupots dataset.
In the evaluation of the mupots dataset, both 'all' and 'matched' forward the bounding box output from detectnet as input to PoseNet?
Isn't the ground-truth bounding box used?

**Comment by mks0601** [comment]
I can't remember clearly, but I guess not.
The test results on mupots dataset depends on the output of [RootNet](https://github.com/mks0601/3DMPPE_ROOTNET_RELEASE), and the output of RootNet is from output of DetectNet, available in [here](https://drive.google.com/drive/folders/1oBluPpX1YV5YLOU7qytbvdUkn0tp_Yyk).

**Comment by seonghyunkim1212** [comment]
Posenet also predicts 3D poses using the bounding box in the link?

**Comment by mks0601** [comment]
Yes

**Comment by seonghyunkim1212** [comment]
Thanks for quick reply!

Seong Hyun Kim
