### ISSUE TITLE
questions about "MuCo-3DHP.json"

### ISSUE THREAD

**Issue by 4AMZGGO1** [mks0601/3DMPPE_POSENET_RELEASE#77]
Thank you so much for providing the downloading link of the dataset ''MuCo''. But I can't totally understand the annotation in the "MuCo-3DHP.json", for example, in the key 'keypoints_cam' , the GT of a keypoint  is  [720.64, -1613.58, 5288.49] , I have no idea why the value of Z axis is so big? Is the unit of the Z aixs diffrent from that of X and Y axis ? So Could  please provide some explanation of the annotation if it's convenient, and my email is xuchenyang@bupt.edu.cn if you need.

**Comment by mks0601** [comment]
The `keypoints_cam` is camera-centered 3D coordinate and its unit is millimeter. ` [720.64, -1613.58, 5288.49]` means the point is 720 mm away from camera in the positive direction of x-axis, 1613.58 mm away from the camera in the negative direction of y-axis, and 5288.49 away from the camera in the positive direction of z-axis. I think the coordinate makes sense.

**Comment by 4AMZGGO1** [comment]
> The `keypoints_cam` is camera-centered 3D coordinate and its unit is millimeter. ` [720.64, -1613.58, 5288.49]` means the point is 720 mm away from camera in the positive direction of x-axis, 1613.58 mm away from the camera in the negative direction of y-axis, and 5288.49 away from the camera in the positive direction of z-axis. I think the coordinate makes sense.

Thank you very much for you so quick and detailed explanation. Deeply Appreciate it again.
