### ISSUE TITLE
Size mismatch when running demo.py

### ISSUE THREAD

**Issue by tiffany0117** [mks0601/3DMPPE_POSENET_RELEASE#78]
Hi,

Thanks for your wonderful works, but when I try to run the demo.py, I got the size mismatch message.  I have downloaded the snapshot_24.pth.tar file you provided on google drive, and put it at the demo folder. Then I got the error message below:

Load checkpoint from ./snapshot_24.pth.tar
Traceback (most recent call last):
  File "demo.py", line 62, in <module>
    model.load_state_dict(ckpt['network'])
  File "C:\Users\NCKU-SEI\anaconda3\envs\pytorch-cpu\lib\site-packages\torch\nn\modules\module.py",
  line 1052, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for DataParallel:
        size mismatch for module.head.final_layer.weight: copying a param with shape torch.Size([1152, 256, 1, 1]) from checkpoint, the shape in current model is torch.Size([1344, 256, 1, 1]).
        size mismatch for module.head.final_layer.bias: copying a param with shape torch.Size([1152]) from checkpoint, the shape in current model is torch.Size([1344]).

Could you tell me how can I fix this?

**Comment by mks0601** [comment]
I think you used a different pre-trained model. Did you download the pre-trained model from [here](https://github.com/mks0601/3DMPPE_POSENET_RELEASE#quick-demo)? The pre-trained model should be in `MuCo-3DHP+MSCOCO` folder of Google drive.

**Comment by tiffany0117** [comment]
Hi, I re-download the pre-trained model, and it works, thanks a lot~
