### ISSUE TITLE
Cannot see 3D Pose

### ISSUE THREAD

**Issue by sumitsarkar1** [mks0601/3DMPPE_POSENET_RELEASE#79]
1.) I ran a yolo v3 for the bbox list
2.) I ran the root net correct to get the depth from camera 
3.) I ran the posenet with bbox list and root list (from rootnet) and was able to see the 2D pose drawn on the image
4.) However I cannot see the second window . I get this warning 

`UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show()
`
5) The 3D points are generated which I checked by printing `output_pose_3d_list` . Where should I check the code to get the 3D plot running. I guess the function vis_3d_multiple_skeleton() in the end of demo.py of posenet is plotting the 3D Pose. Please any suggestions

**Comment by mks0601** [comment]
Maybe you are running the codes on ssh? You should use some X-server things to open windows

**Comment by sumitsarkar1** [comment]
I solved it by `sudo apt install python3-tk` ..thanx for the response
