### ISSUE TITLE
cannot start training if I change the training set

### ISSUE THREAD

**Issue by wangzheallen** [mks0601/3DMPPE_POSENET_RELEASE#8]
it just stuck there if I change the training set from H36m to H36M + MPII.

**Comment by wangzheallen** [comment]
and the model https://cv.snu.ac.kr/research/3DMPPE/model/PoseNet/human3.6m/p2/snapshot24.pth.tar is mising

**Comment by mks0601** [comment]
model url is fixed. What do you mean by stuck?

**Comment by wangzheallen** [comment]
Thanks for response, it is  much slower than training only on H36M

**Comment by mks0601** [comment]
I found that in some machines, creating separate data iterator gives slow training speed. You can combine separated data iterator to single iterator. However, I'm not sure that would give the same accuracy.

**Comment by mks0601** [comment]
Or, you can set frame sampling ratio from 5 to 50 when training mode on Human3.6M. I found that there is marginal performance difference.
