### ISSUE TITLE
3D pose estimation on Video

### ISSUE THREAD

**Issue by sumitsarkar1** [mks0601/3DMPPE_POSENET_RELEASE#80]
1.) I am able to run 3D pose estimate on single images.
2.) For running on videos I need to run them on multiple images (frames) I guess
3.) For every frame I need to cumpute `root_depth_list` using RootNet
4.) How to integrate Posenet and RootNet code (by code I mean the demo.py for both) . Like RootNet and Posenet uses different versions of `get_pose_net()` . I am a bit new to Python, so please suggest how to combine Rootnet and Posenet for per frame processing

**Comment by mks0601** [comment]
You'd better use os.system(cmd).
For example, 
```
os.system('cd RootNet')
os.system('python demo.py --gpu 0') # save root_depth_list in txt format
os.system('cd ../PoseNet')
os.system('python demo.py --gpu 0') # load the saved root_depth list
```

**Comment by sumitsarkar1** [comment]
Thnx...I will try this...just curious like is it a good idea for videos/webcams running at 20 fps

**Comment by mks0601** [comment]
Depends on the running time of the human detection. You can see running time report in the paper.
