### ISSUE TITLE
Failed to extract the human3.6m dataset.

### ISSUE THREAD

**Issue by JanaldoChen** [mks0601/3DMPPE_POSENET_RELEASE#81]
I downloaded all the compressed files of human3.6m dataset. When I run the script `extract_targz.sh,` 
![image](https://user-images.githubusercontent.com/44859515/104816399-ddb4a500-5855-11eb-9661-e276ed62eb56.png)
only this part of the image content is decompressed:
![image](https://user-images.githubusercontent.com/44859515/104816404-e907d080-5855-11eb-94a1-6cbd88c0c877.png)

**Comment by mks0601** [comment]
Please check md5sum.

52b44ed6300ef6ea4dd8ea30d90714f5  images.tar.gzaa
cce49ddb91872fe2f3517e1e49c551fd  images.tar.gzab
4dc95cdbf0ce61b70a768f4ba7a8b208  images.tar.gzac
25bfba5c62afd0d22b1de5c440d62537  images.tar.gzad
917a61552e64aa855445ff4ba487c883  images.tar.gzae
00ee4067f3b0a28ab9e1112da63d5f95  images.tar.gzaf
e93a270451643f49da9b6e0bf86e7859  images.tar.gzag

**Comment by JanaldoChen** [comment]
Thanks for your response! I check the md5sum, it's wrong. So I download again, It's right now.
