### ISSUE TITLE
transform.Normalize

### ISSUE THREAD

**Issue by kdh4672** [mks0601/3DMPPE_POSENET_RELEASE#83]
At config file line 37, there is codes like:  
 
> pixel_mean = (0.485, 0.456, 0.406)
>  pixel_std = (0.229, 0.224, 0.225)

I read your previous  reply about this issue which is now closed:
you said It's from Imagenet dataset

However, I have a question:
For Human3.6M, MuCo, ... or Custom dataset, Dose this 'fixed Normalize' have a effect?

**Comment by mks0601** [comment]
You don't have to take care this much. This is just a convention and it might be effective becasue the resnet weigths are from imagenet pre-trained ones.

**Comment by kdh4672** [comment]
Ah-ha I got it! Thank you..
