### ISSUE TITLE
How to run mpii_mupots_multiperson_eval.m(extracted from testing MuPoTS-3D dataset) ?

### ISSUE THREAD

**Issue by kdh4672** [mks0601/3DMPPE_POSENET_RELEASE#84]
Should I use Matlab Program?

Is there another way to run this file?

**Comment by mks0601** [comment]
You should use Matlab. This evaluation script is a slightly hacked version of the official Matlab evaluation script.

**Comment by kdh4672** [comment]
Thank you for your answer.

And I got a new question, at mpii_mupots_multiperson_eval.m there is a comment like:

`EVALUATION_MODE = eval_mode; % 0 = evaluate all annotated persons, 1 = evaluate only predictions matched to annotations
`

I cannot exact difference between 'all annotated persons'  and 'only predictions matched to annotations'

Can I learn about that in more detail?

**Comment by mks0601** [comment]
This is to reduce false positive I guess.
As I said, I did not write this script and the evaluation protocol is also already built in the script.

**Comment by kdh4672** [comment]
Ah ha.. I got it Thank you!
