### ISSUE TITLE
Images for augmentation (when generating the MuCo dataset)

### ISSUE THREAD

**Issue by Qihao067** [mks0601/3DMPPE_POSENET_RELEASE#86]
Hi, nice job!

I am trying to generate new MoCo data since the data you provided lacks some labels we need.  So I am wondering if you could share the background textures and the foreground textures you used when generating the augmented data? We want to make the new dataset as similar to yours as possible.

Thank you in advance!

**Comment by mks0601** [comment]
Sorry, I can't clearly remember :( I think I used MSCOCO images without humans for the background texture. Also, I think I didn't augmented the foreground.

**Comment by Qihao067** [comment]
Oh, I see. Thanks!
