### ISSUE TITLE
There were different results in two different environments

### ISSUE THREAD

**Issue by applech666** [mks0601/3DMPPE_POSENET_RELEASE#89]
Hi, first of all, thank you for your great work.
There were different results in two different environments. 

1. windows10, cuda9, torch=1.1, I can get a better result.
2.  ubuntu16.04 cuda10.1 torch1.4, I can get another result.
Why do you think the same code gets inconsistent results in two environments?

thanks!

**Comment by mks0601** [comment]
I haven't tested this code on window machines... could you use the same torch versions?

**Comment by applech666** [comment]
windows10, cuda9, torch=1.1, In my opinion, I achieved a perfect result.
But the same code doesn't work very well in either of the following environments:
1. ubuntu16.04 cuda10 torch1.1,
2. ubuntu cuda10.1 torch1.4,
Is it the CUDA version that affects the reasoning effect of the model?

**Comment by mks0601** [comment]
I guess the reason is a different version of torchvision? Several people said that different torchvision version make the batch normalization layer work different. Could you check the torchvision version?

**Comment by applech666** [comment]
I just tried it, and on Linux, torchvision(0.4.1) stays the same as Windows, but it still doesn't improve

**Comment by applech666** [comment]
supplement:  ubuntu cuda=10.1 torch=1.3 torchvision=0.4.1

**Comment by mks0601** [comment]
Sorry I don't get reasons :( You'd better update torch and torchvision

**Comment by applech666** [comment]
I've solved the problem. On Linux, due to my image data set out of order.
Thank you for your valuable time support

**Comment by mks0601** [comment]
Good!
