### ISSUE TITLE
issue about bbox_human36m_output.json and bbox_mupots_output.json.

### ISSUE THREAD

**Issue by ch1998** [mks0601/3DMPPE_POSENET_RELEASE#91]
Thanks your work.
I can't find the link to download the bbox_human36m_output.json in README and bbox_mupots_output.json.
can you give me some suggest?

**Comment by mks0601** [comment]
You can download them from [here](https://github.com/mks0601/3DMPPE_POSENET_RELEASE#results).
```
Bounding boxs (from DetectNet) and root joint coordintates (from RootNet) of Human3.6M, MSCOCO, and MuPoTS-3D dataset in here.
```

**Comment by ch1998** [comment]
I get ot , thanks to your reply.
