### ISSUE TITLE
How to pass the current epoch to the backbone resnet?

### ISSUE THREAD

**Issue by KamiCalcium** [mks0601/3DMPPE_POSENET_RELEASE#96]
Hi,

I was trying to add another convolution kernel before the convolution in the posenet backbone. And there is a parameter updated in that kernel function based on the epoch number. It's like a decay factor, when epoch = 0 it is 1 and epoch *= 0.9 every 10 epochs. However I couldn't find a proper way to pass the epoch parameter. 

In base.py, I see this:
https://github.com/mks0601/3DMPPE_POSENET_RELEASE/blob/3f92ebaef214a0eb1574b7265e836456fbf3508a/common/base.py#L123
This is where we initialize the model, this is under the function._make_model(). 
I did some changes like:
```
model = get_pose_net(cfg, True, self.joint_num, epoch)
```
But in train.py, unlike trainer.set_lr(epoch) which is in the for loop of epoch, we only call the trainer._make_model() one time at the very first beginning outside the for loop:
https://github.com/mks0601/3DMPPE_POSENET_RELEASE/blob/3f92ebaef214a0eb1574b7265e836456fbf3508a/main/train.py#L34

So the epoch number cannot be updated properly if I pass it thru the _make_model(). 

How can I properly pass the epoch number to the posenet model?

**Comment by mks0601** [comment]
Hi, so you want to pass epoch number during the training stage. The epoch number should be changed in the training stage. Am I right?

**Comment by KamiCalcium** [comment]
> Hi, so you want to pass epoch number during the training stage. The epoch number should be changed in the training stage. Am I right?

Yes, that's correct

**Comment by mks0601** [comment]
Why not pass the epoch number using forward function?
In [here](https://github.com/mks0601/3DMPPE_POSENET_RELEASE/blob/3f92ebaef214a0eb1574b7265e836456fbf3508a/main/train.py#L50), you can pass the epoch number by 
```
loss_coord = trainer.model(epoch, input_img, target)
```

and change [this line](https://github.com/mks0601/3DMPPE_POSENET_RELEASE/blob/3f92ebaef214a0eb1574b7265e836456fbf3508a/main/model.py#L89)
to
```
def forward(self, epoch, input_img, target=None):
```

**Comment by KamiCalcium** [comment]
> Hi, so you want to pass epoch number during the training stage. The epoch number should be changed in the training stage. Am I right?

I now do something like this, it looks like it is training, but I'm not sure after epoch 0, will the epoch number still be updated:

In train.py:
```
def main():
    
    # argument parse and create log
    args = parse_args()
    cfg.set_args(args.gpu_ids, args.continue_train)
    cudnn.fastest = True
    cudnn.benchmark = True

    trainer = Trainer()
    trainer._make_batch_generator()
    trainer._make_model(0)

```

In base.py:

```
Class Trainer(Base):
...
...
    def _make_model(self, epoch):
            # prepare network
            if epoch != 0:
                epoch = self.epoch
            self.logger.info("Creating graph and optimizer...")
            model = get_pose_net(cfg, True, self.joint_num, epoch)
```

Also I did the according change in the get_pose_net function in model. Will this work?

**Comment by KamiCalcium** [comment]
> Why not pass the epoch number using forward function?
> In [here](https://github.com/mks0601/3DMPPE_POSENET_RELEASE/blob/3f92ebaef214a0eb1574b7265e836456fbf3508a/main/train.py#L50), you can pass the epoch number by
> 
> ```
> loss_coord = trainer.model(epoch, input_img, target)
> ```
> 
> and change [this line](https://github.com/mks0601/3DMPPE_POSENET_RELEASE/blob/3f92ebaef214a0eb1574b7265e836456fbf3508a/main/model.py#L89)
> to
> 
> ```
> def forward(self, epoch, input_img, target=None):
> ```

Cool! After my current training I will try this and update you. Thx for your quick response!

**Comment by KamiCalcium** [comment]
> Why not pass the epoch number using forward function?
> In [here](https://github.com/mks0601/3DMPPE_POSENET_RELEASE/blob/3f92ebaef214a0eb1574b7265e836456fbf3508a/main/train.py#L50), you can pass the epoch number by
> 
> ```
> loss_coord = trainer.model(epoch, input_img, target)
> ```
> 
> and change [this line](https://github.com/mks0601/3DMPPE_POSENET_RELEASE/blob/3f92ebaef214a0eb1574b7265e836456fbf3508a/main/model.py#L89)
> to
> 
> ```
> def forward(self, epoch, input_img, target=None):
> ```

In https://github.com/mks0601/3DMPPE_POSENET_RELEASE/blob/3f92ebaef214a0eb1574b7265e836456fbf3508a/main/model.py#L107,

the get_pose_net function is not under the Class ResPoseNet. I added the epoch to the forward function as you suggested, but how to pass it to the get_pose_net function?

**Comment by mks0601** [comment]
```
def get_pose_net(cfg, is_train, joint_num, epoch): 
```
```
model = ResPoseNet(backbone, head_net, joint_num, epoch)
```

**Comment by KamiCalcium** [comment]
> ```
> def get_pose_net(cfg, is_train, joint_num, epoch): 
> ```
> 
> ```
> model = ResPoseNet(backbone, head_net, joint_num, epoch)
> ```

It returns 'Trainer' object has no attribute 'epoch'. Since we first call trainer._make_model() outside the epoch for loop. The parameter epoch has not been defined yet

**Comment by mks0601** [comment]
Then, you can follow [this kind of function](https://github.com/mks0601/3DMPPE_POSENET_RELEASE/blob/3f92ebaef214a0eb1574b7265e836456fbf3508a/main/train.py#L39).
Or you can make another function? I don't think what you want is very hard.. Give it a try :)

**Comment by KamiCalcium** [comment]
> Then, you can follow [this kind of function](https://github.com/mks0601/3DMPPE_POSENET_RELEASE/blob/3f92ebaef214a0eb1574b7265e836456fbf3508a/main/train.py#L39).
> Or you can make another function? I don't think what you want is very hard.. Give it a try :)

Yes. The thing that I'm confused with is that it seems trainer._make_model() is only called once at the very first beginning unlike set_lr() is called every epoch. So I don't know if I change anything in trainer._make_model() will make sense or will the epoch number get updated. If this can be clarified by you it will be very helpful for me.

I did a try like I said in https://github.com/mks0601/3DMPPE_POSENET_RELEASE/issues/96#issuecomment-882083116. Waiting for the training now and test the model :) Thanks!
